"""chatto-bot: Python bot framework for Chatto."""

from .version import __version__
from .bot import Bot
from .client import Client, GraphQLError, login
from .cog import Cog
from .command import Command, CommandError, command
from .config import BotConfig
from .context import Context
from .event import EventHandler, on_event
from .middleware import MiddlewareChain
from .types import (
    # Leaf types
    Attachment,
    LinkPreview,
    Reaction,
    SpaceEvent,
    User,
    VideoProcessing,
    VideoProcessingVariant,
    # Unions
    EventType,
    InstanceInnerEvent,
    SpaceInnerEvent,
    # Catch-all
    UnknownEvent,
    # Per-space inner events
    CallParticipantJoinedEvent,
    CallParticipantLeftEvent,
    MessageDeletedEvent,
    MessagePostedEvent,
    MessageUpdatedEvent,
    PresenceChangedEvent,
    ReactionAddedEvent,
    ReactionRemovedEvent,
    RoomArchivedEvent,
    RoomDeletedEvent,
    RoomUnarchivedEvent,
    RoomUpdatedEvent,
    SpaceMemberDeletedEvent,
    UserJoinedRoomEvent,
    UserLeftRoomEvent,
    UserTypingEvent,
    VideoProcessingCompletedEvent,
    # Instance inner events
    InstanceConfigUpdatedEvent,
    InstanceUserPreferencesUpdatedEvent,
    MentionNotificationEvent,
    NewDirectMessageNotificationEvent,
    NewMessageInSpaceEvent,
    NotificationCreatedEvent,
    NotificationDismissedEvent,
    NotificationLevelChangedEvent,
    RoomLayoutUpdatedEvent,
    RoomMarkedAsReadEvent,
    SessionTerminatedEvent,
    SpaceCreatedEvent,
    SpaceDeletedEvent,
    SpaceUpdatedEvent,
    ThreadFollowChangedEvent,
    UserJoinedSpaceEvent,
    UserLeftSpaceEvent,
    UserProfileUpdatedEvent,
)

__all__ = [
    "Bot",
    "Client",
    "GraphQLError",
    "login",
    "Cog",
    "Command",
    "CommandError",
    "command",
    "BotConfig",
    "Context",
    "EventHandler",
    "on_event",
    "MiddlewareChain",
    "__version__",
    # Leaf types
    "Attachment",
    "LinkPreview",
    "Reaction",
    "SpaceEvent",
    "User",
    "VideoProcessing",
    "VideoProcessingVariant",
    # Unions
    "EventType",
    "InstanceInnerEvent",
    "SpaceInnerEvent",
    "UnknownEvent",
    # Per-space inner events
    "CallParticipantJoinedEvent",
    "CallParticipantLeftEvent",
    "MessageDeletedEvent",
    "MessagePostedEvent",
    "MessageUpdatedEvent",
    "PresenceChangedEvent",
    "ReactionAddedEvent",
    "ReactionRemovedEvent",
    "RoomArchivedEvent",
    "RoomDeletedEvent",
    "RoomUnarchivedEvent",
    "RoomUpdatedEvent",
    "SpaceMemberDeletedEvent",
    "UserJoinedRoomEvent",
    "UserLeftRoomEvent",
    "UserTypingEvent",
    "VideoProcessingCompletedEvent",
    # Instance inner events
    "InstanceConfigUpdatedEvent",
    "InstanceUserPreferencesUpdatedEvent",
    "MentionNotificationEvent",
    "NewDirectMessageNotificationEvent",
    "NewMessageInSpaceEvent",
    "NotificationCreatedEvent",
    "NotificationDismissedEvent",
    "NotificationLevelChangedEvent",
    "RoomLayoutUpdatedEvent",
    "RoomMarkedAsReadEvent",
    "SessionTerminatedEvent",
    "SpaceCreatedEvent",
    "SpaceDeletedEvent",
    "SpaceUpdatedEvent",
    "ThreadFollowChangedEvent",
    "UserJoinedSpaceEvent",
    "UserLeftSpaceEvent",
    "UserProfileUpdatedEvent",
]
