"""chatto-bot: Python bot framework for Chatto."""

from .version import __version__
from .bot import Bot
from .client import ChattoError, Client, Unauthenticated
from .cog import Cog
from .command import Command, CommandError, command
from .config import BotConfig
from .context import Context
from .event import EventHandler, on_event
from .middleware import MiddlewareChain
from .timestamps import TimestampToken, format_timestamp_token, parse_timestamp_tokens
from .transport import AuthError, Transport
from .types import (
    # Leaf types
    Attachment,
    CustomUserStatus,
    LinkPreview,
    Reaction,
    RoomEvent,
    SocialPostAuthor,
    SocialPostExternalLink,
    SocialPostImage,
    SocialPostPreview,
    ThreadSummary,
    ThreadViewerState,
    User,
    VideoProcessing,
    VideoProcessingVariant,
    # Unions
    EventType,
    # Catch-all
    UnknownEvent,
    # Live realtime.v1 events
    AssetDeletedEvent,
    AssetProcessingFailedEvent,
    AssetProcessingStartedEvent,
    CallEndedEvent,
    CallParticipantJoinedEvent,
    CallParticipantLeftEvent,
    CallStartedEvent,
    MentionNotificationEvent,
    MessageDeletedEvent,
    MessagePostedEvent,
    MessageUpdatedEvent,
    NewDirectMessageNotificationEvent,
    NotificationCreatedEvent,
    NotificationDismissedEvent,
    NotificationLevelChangedEvent,
    PresenceChangedEvent,
    ReactionAddedEvent,
    ReactionRemovedEvent,
    RoomArchivedEvent,
    RoomCreatedEvent,
    RoomDeletedEvent,
    RoomGroupsUpdatedEvent,
    RoomMarkedAsReadEvent,
    RoomUnarchivedEvent,
    RoomUniversalChangedEvent,
    RoomUpdatedEvent,
    ServerMemberDeletedEvent,
    ServerUpdatedEvent,
    ServerUserPreferencesUpdatedEvent,
    SessionTerminatedEvent,
    ThreadCreatedEvent,
    ThreadFollowChangedEvent,
    UserCustomStatusClearedEvent,
    UserCustomStatusSetEvent,
    UserJoinedRoomEvent,
    UserLeftRoomEvent,
    UserProfileUpdatedEvent,
    UserTypingEvent,
    VideoProcessingCompletedEvent,
    # Retired (no realtime.v1 source; kept for warn_if_retired_event_name())
    HeartbeatEvent,
    MentionStatusClearedEvent,
    RETIRED_EVENT_NAMES,
    ServerConfigUpdatedEvent,
    UserCreatedEvent,
    UserDeletedEvent,
    event_name,
    format_cursor,
    parse_envelope,
    warn_if_retired_event_name,
)

__all__ = [
    "Bot",
    "ChattoError",
    "Client",
    "Unauthenticated",
    "AuthError",
    "Transport",
    "Cog",
    "Command",
    "CommandError",
    "command",
    "BotConfig",
    "Context",
    "EventHandler",
    "on_event",
    "MiddlewareChain",
    "__version__",
    # Timestamps (FDR-030)
    "TimestampToken",
    "format_timestamp_token",
    "parse_timestamp_tokens",
    # Leaf types
    "Attachment",
    "CustomUserStatus",
    "LinkPreview",
    "Reaction",
    "RoomEvent",
    "SocialPostAuthor",
    "SocialPostExternalLink",
    "SocialPostImage",
    "SocialPostPreview",
    "ThreadSummary",
    "ThreadViewerState",
    "User",
    "VideoProcessing",
    "VideoProcessingVariant",
    # Unions
    "EventType",
    "UnknownEvent",
    # Live realtime.v1 events
    "AssetDeletedEvent",
    "AssetProcessingFailedEvent",
    "AssetProcessingStartedEvent",
    "CallEndedEvent",
    "CallParticipantJoinedEvent",
    "CallParticipantLeftEvent",
    "CallStartedEvent",
    "MentionNotificationEvent",
    "MessageDeletedEvent",
    "MessagePostedEvent",
    "MessageUpdatedEvent",
    "NewDirectMessageNotificationEvent",
    "NotificationCreatedEvent",
    "NotificationDismissedEvent",
    "NotificationLevelChangedEvent",
    "PresenceChangedEvent",
    "ReactionAddedEvent",
    "ReactionRemovedEvent",
    "RoomArchivedEvent",
    "RoomCreatedEvent",
    "RoomDeletedEvent",
    "RoomGroupsUpdatedEvent",
    "RoomMarkedAsReadEvent",
    "RoomUnarchivedEvent",
    "RoomUniversalChangedEvent",
    "RoomUpdatedEvent",
    "ServerMemberDeletedEvent",
    "ServerUpdatedEvent",
    "ServerUserPreferencesUpdatedEvent",
    "SessionTerminatedEvent",
    "ThreadCreatedEvent",
    "ThreadFollowChangedEvent",
    "UserCustomStatusClearedEvent",
    "UserCustomStatusSetEvent",
    "UserJoinedRoomEvent",
    "UserLeftRoomEvent",
    "UserProfileUpdatedEvent",
    "UserTypingEvent",
    "VideoProcessingCompletedEvent",
    # Retired
    "HeartbeatEvent",
    "MentionStatusClearedEvent",
    "RETIRED_EVENT_NAMES",
    "ServerConfigUpdatedEvent",
    "UserCreatedEvent",
    "UserDeletedEvent",
    "event_name",
    "format_cursor",
    "parse_envelope",
    "warn_if_retired_event_name",
]
