# Generated from chatto/api/v1/asset_uploads.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import asset_uploads_pb
from .asset_uploads_pb import CancelUploadRequest, CancelUploadResponse, CompleteUploadRequest, CompleteUploadResponse, CreateUploadRequest, CreateUploadResponse, GetUploadRequest, GetUploadResponse, UploadChunkRequest, UploadChunkResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class AssetUploadService(Protocol):
    """
    Creates room-scoped attachment assets through chunked ConnectRPC uploads.
    """
    async def create_upload(self, request: CreateUploadRequest, ctx: RequestContext[CreateUploadRequest, CreateUploadResponse], /) -> CreateUploadResponse:
        """
        Starts a room-scoped attachment upload for the authenticated user.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def upload_chunk(self, request: UploadChunkRequest, ctx: RequestContext[UploadChunkRequest, UploadChunkResponse], /) -> UploadChunkResponse:
        """
        Appends one chunk at the upload's current committed offset.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_upload(self, request: GetUploadRequest, ctx: RequestContext[GetUploadRequest, GetUploadResponse], /) -> GetUploadResponse:
        """
        Reads current upload state for retry or resume.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def complete_upload(self, request: CompleteUploadRequest, ctx: RequestContext[CompleteUploadRequest, CompleteUploadResponse], /) -> CompleteUploadResponse:
        """
        Verifies the completed upload and creates the attachment asset.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def cancel_upload(self, request: CancelUploadRequest, ctx: RequestContext[CancelUploadRequest, CancelUploadResponse], /) -> CancelUploadResponse:
        """
        Cancels an incomplete upload and releases temporary storage.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in asset_uploads_pb.desc().services if s.type_name == 'chatto.api.v1.AssetUploadService')

class AssetUploadServiceASGIApplication(ConnectASGIApplication[AssetUploadService]):
    def __init__(
        self,
        service: AssetUploadService | AsyncGenerator[AssetUploadService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.AssetUploadService/CreateUpload": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateUpload",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=CreateUploadRequest,
                        output=CreateUploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_upload,
                ),
                "/chatto.api.v1.AssetUploadService/UploadChunk": Endpoint.unary(
                    method=MethodInfo(
                        name="UploadChunk",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=UploadChunkRequest,
                        output=UploadChunkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.upload_chunk,
                ),
                "/chatto.api.v1.AssetUploadService/GetUpload": Endpoint.unary(
                    method=MethodInfo(
                        name="GetUpload",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=GetUploadRequest,
                        output=GetUploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_upload,
                ),
                "/chatto.api.v1.AssetUploadService/CompleteUpload": Endpoint.unary(
                    method=MethodInfo(
                        name="CompleteUpload",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=CompleteUploadRequest,
                        output=CompleteUploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.complete_upload,
                ),
                "/chatto.api.v1.AssetUploadService/CancelUpload": Endpoint.unary(
                    method=MethodInfo(
                        name="CancelUpload",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=CancelUploadRequest,
                        output=CancelUploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.cancel_upload,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.AssetUploadService"


class AssetUploadServiceClient(ConnectClient):
    """
    Creates room-scoped attachment assets through chunked ConnectRPC uploads.
    """
    async def create_upload(
        self,
        request: CreateUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateUploadResponse:
        """
        Starts a room-scoped attachment upload for the authenticated user.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateUpload",
                service_name="chatto.api.v1.AssetUploadService",
                input=CreateUploadRequest,
                output=CreateUploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def upload_chunk(
        self,
        request: UploadChunkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UploadChunkResponse:
        """
        Appends one chunk at the upload's current committed offset.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadChunk",
                service_name="chatto.api.v1.AssetUploadService",
                input=UploadChunkRequest,
                output=UploadChunkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_upload(
        self,
        request: GetUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetUploadResponse:
        """
        Reads current upload state for retry or resume.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUpload",
                service_name="chatto.api.v1.AssetUploadService",
                input=GetUploadRequest,
                output=GetUploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def complete_upload(
        self,
        request: CompleteUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CompleteUploadResponse:
        """
        Verifies the completed upload and creates the attachment asset.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CompleteUpload",
                service_name="chatto.api.v1.AssetUploadService",
                input=CompleteUploadRequest,
                output=CompleteUploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def cancel_upload(
        self,
        request: CancelUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CancelUploadResponse:
        """
        Cancels an incomplete upload and releases temporary storage.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelUpload",
                service_name="chatto.api.v1.AssetUploadService",
                input=CancelUploadRequest,
                output=CancelUploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class AssetUploadServiceSync(Protocol):
    """
    Creates room-scoped attachment assets through chunked ConnectRPC uploads.
    """
    def create_upload(self, request: CreateUploadRequest, ctx: RequestContext[CreateUploadRequest, CreateUploadResponse], /) -> CreateUploadResponse:
        """
        Starts a room-scoped attachment upload for the authenticated user.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def upload_chunk(self, request: UploadChunkRequest, ctx: RequestContext[UploadChunkRequest, UploadChunkResponse], /) -> UploadChunkResponse:
        """
        Appends one chunk at the upload's current committed offset.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_upload(self, request: GetUploadRequest, ctx: RequestContext[GetUploadRequest, GetUploadResponse], /) -> GetUploadResponse:
        """
        Reads current upload state for retry or resume.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def complete_upload(self, request: CompleteUploadRequest, ctx: RequestContext[CompleteUploadRequest, CompleteUploadResponse], /) -> CompleteUploadResponse:
        """
        Verifies the completed upload and creates the attachment asset.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def cancel_upload(self, request: CancelUploadRequest, ctx: RequestContext[CancelUploadRequest, CancelUploadResponse], /) -> CancelUploadResponse:
        """
        Cancels an incomplete upload and releases temporary storage.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in asset_uploads_pb.desc().services if s.type_name == 'chatto.api.v1.AssetUploadService')

class AssetUploadServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AssetUploadServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.AssetUploadService/CreateUpload": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateUpload",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=CreateUploadRequest,
                        output=CreateUploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_upload,
                ),
                "/chatto.api.v1.AssetUploadService/UploadChunk": EndpointSync.unary(
                    method=MethodInfo(
                        name="UploadChunk",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=UploadChunkRequest,
                        output=UploadChunkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.upload_chunk,
                ),
                "/chatto.api.v1.AssetUploadService/GetUpload": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetUpload",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=GetUploadRequest,
                        output=GetUploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_upload,
                ),
                "/chatto.api.v1.AssetUploadService/CompleteUpload": EndpointSync.unary(
                    method=MethodInfo(
                        name="CompleteUpload",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=CompleteUploadRequest,
                        output=CompleteUploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.complete_upload,
                ),
                "/chatto.api.v1.AssetUploadService/CancelUpload": EndpointSync.unary(
                    method=MethodInfo(
                        name="CancelUpload",
                        service_name="chatto.api.v1.AssetUploadService",
                        input=CancelUploadRequest,
                        output=CancelUploadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.cancel_upload,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.AssetUploadService"


class AssetUploadServiceClientSync(ConnectClientSync):
    """
    Creates room-scoped attachment assets through chunked ConnectRPC uploads.
    """
    def create_upload(
        self,
        request: CreateUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateUploadResponse:
        """
        Starts a room-scoped attachment upload for the authenticated user.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateUpload",
                service_name="chatto.api.v1.AssetUploadService",
                input=CreateUploadRequest,
                output=CreateUploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def upload_chunk(
        self,
        request: UploadChunkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UploadChunkResponse:
        """
        Appends one chunk at the upload's current committed offset.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadChunk",
                service_name="chatto.api.v1.AssetUploadService",
                input=UploadChunkRequest,
                output=UploadChunkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_upload(
        self,
        request: GetUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetUploadResponse:
        """
        Reads current upload state for retry or resume.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUpload",
                service_name="chatto.api.v1.AssetUploadService",
                input=GetUploadRequest,
                output=GetUploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def complete_upload(
        self,
        request: CompleteUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CompleteUploadResponse:
        """
        Verifies the completed upload and creates the attachment asset.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CompleteUpload",
                service_name="chatto.api.v1.AssetUploadService",
                input=CompleteUploadRequest,
                output=CompleteUploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def cancel_upload(
        self,
        request: CancelUploadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CancelUploadResponse:
        """
        Cancels an incomplete upload and releases temporary storage.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelUpload",
                service_name="chatto.api.v1.AssetUploadService",
                input=CancelUploadRequest,
                output=CancelUploadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
