# Generated from chatto/api/v1/link_previews.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from ....buf.validate import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile


_FetchLinkPreviewRequestFields: TypeAlias = Literal["url"]

class FetchLinkPreviewRequest(Message[_FetchLinkPreviewRequestFields]):
    """
    Request to fetch server-side link preview metadata for a URL.

    ```proto
    message chatto.api.v1.FetchLinkPreviewRequest
    ```

    Attributes:
        url:
            URL to preview.

            ```proto
            string url = 1;
            ```
    """

    __slots__ = ("url",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            url: str = "",
        ) -> None:
            pass

        url: str

_LinkPreviewFields: TypeAlias = Literal["url", "title", "description", "image_url", "image_asset_id", "site_name", "embed_type", "embed_id"]

class LinkPreview(Message[_LinkPreviewFields]):
    """
    Link preview metadata used by message composers and room timeline events.

    Clients should treat optional metadata as unavailable when absent. Message
    creation accepts only the preview_token returned by FetchLinkPreview, not
    client-provided metadata fields.

    ```proto
    message chatto.api.v1.LinkPreview
    ```

    Attributes:
        url:
            Previewed URL.

            ```proto
            string url = 1;
            ```
        title:
            Page or embed title.

            ```proto
            optional string title = 2;
            ```
        description:
            Page or embed description.

            ```proto
            optional string description = 3;
            ```
        image_url:
            Preview image URL, when available.

            ```proto
            optional string image_url = 4;
            ```
        image_asset_id:
            Existing server asset ID for the preview image, when cached or stored with
            the message.

            ```proto
            optional string image_asset_id = 5;
            ```
        site_name:
            Site name, when known.

            ```proto
            optional string site_name = 6;
            ```
        embed_type:
            Embed provider or type, when recognized.

            ```proto
            optional string embed_type = 7;
            ```
        embed_id:
            Provider-specific embed ID, when recognized.

            ```proto
            optional string embed_id = 8;
            ```
    """

    __slots__ = ("url", "title", "description", "image_url", "image_asset_id", "site_name", "embed_type", "embed_id")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            url: str = "",
            title: str | None = None,
            description: str | None = None,
            image_url: str | None = None,
            image_asset_id: str | None = None,
            site_name: str | None = None,
            embed_type: str | None = None,
            embed_id: str | None = None,
        ) -> None:
            pass

        url: str
        title: str
        description: str
        image_url: str
        image_asset_id: str
        site_name: str
        embed_type: str
        embed_id: str

_FetchLinkPreviewResponseFields: TypeAlias = Literal["preview", "preview_token"]

class FetchLinkPreviewResponse(Message[_FetchLinkPreviewResponseFields]):
    """
    Result of fetching link preview metadata.

    ```proto
    message chatto.api.v1.FetchLinkPreviewResponse
    ```

    Attributes:
        preview:
            Preview metadata, or absent when the URL cannot be previewed.

            ```proto
            optional chatto.api.v1.LinkPreview preview = 1;
            ```
        preview_token:
            Short-lived opaque token to pass to CreateMessage.link_preview_token when
            the user posts this preview.

            ```proto
            string preview_token = 2;
            ```
    """

    __slots__ = ("preview", "preview_token")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            preview: LinkPreview | None = None,
            preview_token: str = "",
        ) -> None:
            pass

        preview: LinkPreview | None
        preview_token: str


_DESC = file_desc(
    b'\n!chatto/api/v1/link_previews.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto"7\n\x17FetchLinkPreviewRequest\x12\x1c\n\x03url\x18\x01 \x01(\tR\x03urlB\n\xbaH\x07r\x05\x10\x01\x18\x80\x10"\xf9\x02\n\x0bLinkPreview\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n\x0bdescription\x18\x03 \x01(\tH\x01R\x0bdescription\x88\x01\x01\x12 \n\timage_url\x18\x04 \x01(\tH\x02R\x08imageUrl\x88\x01\x01\x12)\n\x0eimage_asset_id\x18\x05 \x01(\tH\x03R\x0cimageAssetId\x88\x01\x01\x12 \n\tsite_name\x18\x06 \x01(\tH\x04R\x08siteName\x88\x01\x01\x12"\n\nembed_type\x18\x07 \x01(\tH\x05R\tembedType\x88\x01\x01\x12\x1e\n\x08embed_id\x18\x08 \x01(\tH\x06R\x07embedId\x88\x01\x01B\x08\n\x06_titleB\x0e\n\x0c_descriptionB\x0c\n\n_image_urlB\x11\n\x0f_image_asset_idB\x0c\n\n_site_nameB\r\n\x0b_embed_typeB\x0b\n\t_embed_id"u\n\x18FetchLinkPreviewResponse\x124\n\x07preview\x18\x01 \x01(\x0b2\x1a.chatto.api.v1.LinkPreviewR\x07preview\x12#\n\rpreview_token\x18\x02 \x01(\tR\x0cpreviewTokenB|\n\x11com.chatto.api.v1B\x11LinkPreviewsProtoP\x01\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3',
    [
        validate_pb.desc(),
    ],
    {
        "FetchLinkPreviewRequest": FetchLinkPreviewRequest,
        "LinkPreview": LinkPreview,
        "FetchLinkPreviewResponse": FetchLinkPreviewResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `chatto/api/v1/link_previews.proto`."""
    return _DESC
