# Generated from chatto/api/v1/member_directory.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.5.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc
from protobuf.wkt import timestamp_pb

from . import pagination_pb, presence_pb, users_pb
from ....buf.validate import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile
    from protobuf.wkt import Timestamp

    from .pagination_pb import PageInfo, PageRequest
    from .presence_pb import PresenceStatus
    from .users_pb import User


_DirectoryMemberFields: TypeAlias = Literal["user", "roles", "created_at"]

class DirectoryMember(Message[_DirectoryMemberFields]):
    """
    Public user/member row used by user directory, room membership, and mention
    surfaces.

    ```proto
    message chatto.api.v1.DirectoryMember
    ```

    Attributes:
        user:
            Public user fields.

            ```proto
            optional chatto.api.v1.User user = 1;
            ```
        roles:
            Explicit roles assigned to the user. Member listings include the virtual
            `everyone` role for parity with Chatto's permission model.

            ```proto
            repeated string roles = 2;
            ```
        created_at:
            Account creation time when known.

            ```proto
            optional google.protobuf.Timestamp created_at = 3;
            ```
    """

    __slots__ = ("user", "roles", "created_at")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            user: User | None = None,
            roles: list[str] | None = None,
            created_at: Timestamp | None = None,
        ) -> None:
            pass

        user: User | None
        roles: list[str]
        created_at: Timestamp | None

_ListMembersRequestFields: TypeAlias = Literal["room_id", "search", "page", "presence_statuses"]

class ListMembersRequest(Message[_ListMembersRequestFields]):
    """
    Request for members of one room.

    ```proto
    message chatto.api.v1.ListMembersRequest
    ```

    Attributes:
        room_id:
            Required. Room whose effective members should be listed. Existing members
            and room.manage holders may list a channel room; other nonmembers need both
            room.list and room.join.

            ```proto
            string room_id = 1;
            ```
        search:
            Optional case-insensitive search against login and display name.

            ```proto
            string search = 2;
            ```
        page:
            Defaults to 250 results when absent or limit is zero. Maximum: 500.

            ```proto
            optional chatto.api.v1.PageRequest page = 5;
            ```
        presence_statuses:
            Optional status filter applied before pagination. Empty means all statuses.
            Select ONLINE, AWAY, and DO_NOT_DISTURB for all connected members.
            Presence can change between pages; use realtime updates to keep it current.

            ```proto
            repeated chatto.api.v1.PresenceStatus presence_statuses = 6 [packed = true];
            ```
    """

    __slots__ = ("room_id", "search", "page", "presence_statuses")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            room_id: str = "",
            search: str = "",
            page: PageRequest | None = None,
            presence_statuses: list[PresenceStatus] | None = None,
        ) -> None:
            pass

        room_id: str
        search: str
        page: PageRequest | None
        presence_statuses: list[PresenceStatus]

_ListMembersResponseFields: TypeAlias = Literal["user_ids", "page"]

class ListMembersResponse(Message[_ListMembersResponseFields]):
    """
    Room membership IDs. Resolve profiles with UserService.BatchGetUsers.
    Empty searches do not read user profiles. Search results require profile
    reads to match names. Both paths use ascending user ID order.

    ```proto
    message chatto.api.v1.ListMembersResponse
    ```

    Attributes:
        user_ids:
            Current member IDs in ascending order. Missing or deleted users are omitted.

            ```proto
            repeated string user_ids = 5;
            ```
        page:
            Page metadata for the members that match both filters.

            ```proto
            optional chatto.api.v1.PageInfo page = 4;
            ```
    """

    __slots__ = ("user_ids", "page")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            user_ids: list[str] | None = None,
            page: PageInfo | None = None,
        ) -> None:
            pass

        user_ids: list[str]
        page: PageInfo | None

_GetMemberRequestFields: TypeAlias = Literal["room_id", "user_id"]

class GetMemberRequest(Message[_GetMemberRequestFields]):
    """
    Request one member of one room by stable user ID.

    ```proto
    message chatto.api.v1.GetMemberRequest
    ```

    Attributes:
        room_id:
            Required room ID.

            ```proto
            string room_id = 1;
            ```
        user_id:
            Required target user ID.

            ```proto
            string user_id = 2;
            ```
    """

    __slots__ = ("room_id", "user_id")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            room_id: str = "",
            user_id: str = "",
        ) -> None:
            pass

        room_id: str
        user_id: str

_GetMemberResponseFields: TypeAlias = Literal["member"]

class GetMemberResponse(Message[_GetMemberResponseFields]):
    """
    Room member response.

    ```proto
    message chatto.api.v1.GetMemberResponse
    ```

    Attributes:
        member:
            Requested room member.

            ```proto
            optional chatto.api.v1.DirectoryMember member = 1;
            ```
    """

    __slots__ = ("member",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            member: DirectoryMember | None = None,
        ) -> None:
            pass

        member: DirectoryMember | None

_BatchGetMembersRequestFields: TypeAlias = Literal["room_id", "user_ids"]

class BatchGetMembersRequest(Message[_BatchGetMembersRequestFields]):
    """
    Request room member rows for a set of stable user IDs.

    ```proto
    message chatto.api.v1.BatchGetMembersRequest
    ```

    Attributes:
        room_id:
            Required room ID.

            ```proto
            string room_id = 1;
            ```
        user_ids:
            Required target user IDs. Unknown IDs and users that are not members of the
            room are omitted from the response.

            ```proto
            repeated string user_ids = 2;
            ```
    """

    __slots__ = ("room_id", "user_ids")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            room_id: str = "",
            user_ids: list[str] | None = None,
        ) -> None:
            pass

        room_id: str
        user_ids: list[str]

_BatchGetMembersResponseFields: TypeAlias = Literal["members"]

class BatchGetMembersResponse(Message[_BatchGetMembersResponseFields]):
    """
    Batch room member response.

    ```proto
    message chatto.api.v1.BatchGetMembersResponse
    ```

    Attributes:
        members:
            Found members. The server preserves first-seen request order and
            de-duplicates repeated IDs.

            ```proto
            repeated chatto.api.v1.DirectoryMember members = 1;
            ```
    """

    __slots__ = ("members",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            members: list[DirectoryMember] | None = None,
        ) -> None:
            pass

        members: list[DirectoryMember]


_DESC = file_desc(
    b'\n$chatto/api/v1/member_directory.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1echatto/api/v1/pagination.proto\x1a\x1cchatto/api/v1/presence.proto\x1a\x19chatto/api/v1/users.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\x8b\x01\n\x0fDirectoryMember\x12\'\n\x04user\x18\x01 \x01(\x0b2\x13.chatto.api.v1.UserR\x04user\x12\x14\n\x05roles\x18\x02 \x03(\tR\x05roles\x129\n\ncreated_at\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampR\tcreatedAt"\x83\x02\n\x12ListMembersRequest\x12 \n\x07room_id\x18\x01 \x01(\tR\x06roomIdB\x07\xbaH\x04r\x02\x10\x01\x12\x1f\n\x06search\x18\x02 \x01(\tR\x06searchB\x07\xbaH\x04r\x02\x18d\x12.\n\x04page\x18\x05 \x01(\x0b2\x1a.chatto.api.v1.PageRequestR\x04page\x12_\n\x11presence_statuses\x18\x06 \x03(\x0e2\x1d.chatto.api.v1.PresenceStatusR\x10presenceStatusesB\x13\xbaH\x10\x92\x01\r\x10\x04\x18\x01"\x07\x82\x01\x04\x10\x01 \x00J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05R\x05limitR\x06offset"\x8f\x01\n\x13ListMembersResponse\x12\x19\n\x08user_ids\x18\x05 \x03(\tR\x07userIds\x12+\n\x04page\x18\x04 \x01(\x0b2\x17.chatto.api.v1.PageInfoR\x04pageJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04R\x07membersR\x0btotal_countR\x08has_more"V\n\x10GetMemberRequest\x12 \n\x07room_id\x18\x01 \x01(\tR\x06roomIdB\x07\xbaH\x04r\x02\x10\x01\x12 \n\x07user_id\x18\x02 \x01(\tR\x06userIdB\x07\xbaH\x04r\x02\x10\x01"K\n\x11GetMemberResponse\x126\n\x06member\x18\x01 \x01(\x0b2\x1e.chatto.api.v1.DirectoryMemberR\x06member"g\n\x16BatchGetMembersRequest\x12 \n\x07room_id\x18\x01 \x01(\tR\x06roomIdB\x07\xbaH\x04r\x02\x10\x01\x12+\n\x08user_ids\x18\x02 \x03(\tR\x07userIdsB\x10\xbaH\r\x92\x01\n\x08\x01\x10d"\x04r\x02\x10\x01"S\n\x17BatchGetMembersResponse\x128\n\x07members\x18\x01 \x03(\x0b2\x1e.chatto.api.v1.DirectoryMemberR\x07membersB\x7f\n\x11com.chatto.api.v1B\x14MemberDirectoryProtoP\x01\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3',
    [
        validate_pb.desc(),
        pagination_pb.desc(),
        presence_pb.desc(),
        users_pb.desc(),
        timestamp_pb.desc(),
    ],
    {
        "DirectoryMember": DirectoryMember,
        "ListMembersRequest": ListMembersRequest,
        "ListMembersResponse": ListMembersResponse,
        "GetMemberRequest": GetMemberRequest,
        "GetMemberResponse": GetMemberResponse,
        "BatchGetMembersRequest": BatchGetMembersRequest,
        "BatchGetMembersResponse": BatchGetMembersResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `chatto/api/v1/member_directory.proto`."""
    return _DESC
