# Generated from chatto/api/v1/member_directory.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .member_directory_pb import BatchGetUsersRequest, BatchGetUsersResponse, GetUserRequest, GetUserResponse, ListUsersRequest, ListUsersResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class UserService(Protocol):
    async def list_users(self, request: ListUsersRequest, ctx: RequestContext[ListUsersRequest, ListUsersResponse]) -> ListUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_user(self, request: GetUserRequest, ctx: RequestContext[GetUserRequest, GetUserResponse]) -> GetUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_get_users(self, request: BatchGetUsersRequest, ctx: RequestContext[BatchGetUsersRequest, BatchGetUsersResponse]) -> BatchGetUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class UserServiceASGIApplication(ConnectASGIApplication[UserService]):
    def __init__(
        self,
        service: UserService | AsyncGenerator[UserService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.UserService/ListUsers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListUsers",
                        service_name="chatto.api.v1.UserService",
                        input=ListUsersRequest,
                        output=ListUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_users,
                ),
                "/chatto.api.v1.UserService/GetUser": Endpoint.unary(
                    method=MethodInfo(
                        name="GetUser",
                        service_name="chatto.api.v1.UserService",
                        input=GetUserRequest,
                        output=GetUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_user,
                ),
                "/chatto.api.v1.UserService/BatchGetUsers": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetUsers",
                        service_name="chatto.api.v1.UserService",
                        input=BatchGetUsersRequest,
                        output=BatchGetUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_users,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.UserService"


class UserServiceClient(ConnectClient):
    async def list_users(
        self,
        request: ListUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="chatto.api.v1.UserService",
                input=ListUsersRequest,
                output=ListUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_user(
        self,
        request: GetUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetUserResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="chatto.api.v1.UserService",
                input=GetUserRequest,
                output=GetUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_users(
        self,
        request: BatchGetUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetUsers",
                service_name="chatto.api.v1.UserService",
                input=BatchGetUsersRequest,
                output=BatchGetUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class UserServiceSync(Protocol):
    def list_users(self, request: ListUsersRequest, ctx: RequestContext[ListUsersRequest, ListUsersResponse]) -> ListUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_user(self, request: GetUserRequest, ctx: RequestContext[GetUserRequest, GetUserResponse]) -> GetUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_get_users(self, request: BatchGetUsersRequest, ctx: RequestContext[BatchGetUsersRequest, BatchGetUsersResponse]) -> BatchGetUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class UserServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: UserServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.UserService/ListUsers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListUsers",
                        service_name="chatto.api.v1.UserService",
                        input=ListUsersRequest,
                        output=ListUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_users,
                ),
                "/chatto.api.v1.UserService/GetUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetUser",
                        service_name="chatto.api.v1.UserService",
                        input=GetUserRequest,
                        output=GetUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_user,
                ),
                "/chatto.api.v1.UserService/BatchGetUsers": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetUsers",
                        service_name="chatto.api.v1.UserService",
                        input=BatchGetUsersRequest,
                        output=BatchGetUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_users,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.UserService"


class UserServiceClientSync(ConnectClientSync):
    def list_users(
        self,
        request: ListUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="chatto.api.v1.UserService",
                input=ListUsersRequest,
                output=ListUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_user(
        self,
        request: GetUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetUserResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="chatto.api.v1.UserService",
                input=GetUserRequest,
                output=GetUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def batch_get_users(
        self,
        request: BatchGetUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetUsers",
                service_name="chatto.api.v1.UserService",
                input=BatchGetUsersRequest,
                output=BatchGetUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
