# Generated from chatto/api/v1/message_search.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import message_search_pb
from .message_search_pb import GetStatusRequest, GetStatusResponse, SearchMessagesRequest, SearchMessagesResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class MessageSearchService(Protocol):
    """
    Searches current message content visible to an authenticated user.
    """
    async def get_status(self, request: GetStatusRequest, ctx: RequestContext[GetStatusRequest, GetStatusResponse], /) -> GetStatusResponse:
        """
        Reports whether the operator enabled Search and whether its provider can
        currently answer. This method remains available when Search is disabled.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def search_messages(self, request: SearchMessagesRequest, ctx: RequestContext[SearchMessagesRequest, SearchMessagesResponse], /) -> SearchMessagesResponse:
        """
        Searches current message bodies in rooms where the caller is a member.
        Scope and grouping are independent, including for direct messages. THREAD
        grouping returns one row per matching root and its replies. Scope, grouping,
        and ordering are part of the cursor scope. Unsupported combinations return
        INVALID_ARGUMENT. Existing requests return individual messages by default.
        Results also require message.read or a matching thread relationship with
        message.read-interactions. Results are authorized and hydrated from current Chatto state
        after provider matching. Returns FAILED_PRECONDITION when Search is
        disabled and UNAVAILABLE when its provider is not ready.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in message_search_pb.desc().services if s.type_name == 'chatto.api.v1.MessageSearchService')

class MessageSearchServiceASGIApplication(ConnectASGIApplication[MessageSearchService]):
    def __init__(
        self,
        service: MessageSearchService | AsyncGenerator[MessageSearchService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.MessageSearchService/GetStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStatus",
                        service_name="chatto.api.v1.MessageSearchService",
                        input=GetStatusRequest,
                        output=GetStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_status,
                ),
                "/chatto.api.v1.MessageSearchService/SearchMessages": Endpoint.unary(
                    method=MethodInfo(
                        name="SearchMessages",
                        service_name="chatto.api.v1.MessageSearchService",
                        input=SearchMessagesRequest,
                        output=SearchMessagesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.search_messages,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.MessageSearchService"


class MessageSearchServiceClient(ConnectClient):
    """
    Searches current message content visible to an authenticated user.
    """
    async def get_status(
        self,
        request: GetStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetStatusResponse:
        """
        Reports whether the operator enabled Search and whether its provider can
        currently answer. This method remains available when Search is disabled.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStatus",
                service_name="chatto.api.v1.MessageSearchService",
                input=GetStatusRequest,
                output=GetStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def search_messages(
        self,
        request: SearchMessagesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SearchMessagesResponse:
        """
        Searches current message bodies in rooms where the caller is a member.
        Scope and grouping are independent, including for direct messages. THREAD
        grouping returns one row per matching root and its replies. Scope, grouping,
        and ordering are part of the cursor scope. Unsupported combinations return
        INVALID_ARGUMENT. Existing requests return individual messages by default.
        Results also require message.read or a matching thread relationship with
        message.read-interactions. Results are authorized and hydrated from current Chatto state
        after provider matching. Returns FAILED_PRECONDITION when Search is
        disabled and UNAVAILABLE when its provider is not ready.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SearchMessages",
                service_name="chatto.api.v1.MessageSearchService",
                input=SearchMessagesRequest,
                output=SearchMessagesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class MessageSearchServiceSync(Protocol):
    """
    Searches current message content visible to an authenticated user.
    """
    def get_status(self, request: GetStatusRequest, ctx: RequestContext[GetStatusRequest, GetStatusResponse], /) -> GetStatusResponse:
        """
        Reports whether the operator enabled Search and whether its provider can
        currently answer. This method remains available when Search is disabled.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def search_messages(self, request: SearchMessagesRequest, ctx: RequestContext[SearchMessagesRequest, SearchMessagesResponse], /) -> SearchMessagesResponse:
        """
        Searches current message bodies in rooms where the caller is a member.
        Scope and grouping are independent, including for direct messages. THREAD
        grouping returns one row per matching root and its replies. Scope, grouping,
        and ordering are part of the cursor scope. Unsupported combinations return
        INVALID_ARGUMENT. Existing requests return individual messages by default.
        Results also require message.read or a matching thread relationship with
        message.read-interactions. Results are authorized and hydrated from current Chatto state
        after provider matching. Returns FAILED_PRECONDITION when Search is
        disabled and UNAVAILABLE when its provider is not ready.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in message_search_pb.desc().services if s.type_name == 'chatto.api.v1.MessageSearchService')

class MessageSearchServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: MessageSearchServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.MessageSearchService/GetStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetStatus",
                        service_name="chatto.api.v1.MessageSearchService",
                        input=GetStatusRequest,
                        output=GetStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_status,
                ),
                "/chatto.api.v1.MessageSearchService/SearchMessages": EndpointSync.unary(
                    method=MethodInfo(
                        name="SearchMessages",
                        service_name="chatto.api.v1.MessageSearchService",
                        input=SearchMessagesRequest,
                        output=SearchMessagesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.search_messages,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.MessageSearchService"


class MessageSearchServiceClientSync(ConnectClientSync):
    """
    Searches current message content visible to an authenticated user.
    """
    def get_status(
        self,
        request: GetStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetStatusResponse:
        """
        Reports whether the operator enabled Search and whether its provider can
        currently answer. This method remains available when Search is disabled.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStatus",
                service_name="chatto.api.v1.MessageSearchService",
                input=GetStatusRequest,
                output=GetStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def search_messages(
        self,
        request: SearchMessagesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SearchMessagesResponse:
        """
        Searches current message bodies in rooms where the caller is a member.
        Scope and grouping are independent, including for direct messages. THREAD
        grouping returns one row per matching root and its replies. Scope, grouping,
        and ordering are part of the cursor scope. Unsupported combinations return
        INVALID_ARGUMENT. Existing requests return individual messages by default.
        Results also require message.read or a matching thread relationship with
        message.read-interactions. Results are authorized and hydrated from current Chatto state
        after provider matching. Returns FAILED_PRECONDITION when Search is
        disabled and UNAVAILABLE when its provider is not ready.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SearchMessages",
                service_name="chatto.api.v1.MessageSearchService",
                input=SearchMessagesRequest,
                output=SearchMessagesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
