# Generated from chatto/api/v1/notifications.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import notifications_pb
from .notifications_pb import BatchDeleteNotificationOccurrencesRequest, BatchDeleteNotificationOccurrencesResponse, BatchGetNotificationOccurrencesRequest, BatchGetNotificationOccurrencesResponse, BatchGetNotificationPoliciesRequest, BatchGetNotificationPoliciesResponse, DeleteAllNotificationOccurrencesRequest, DeleteAllNotificationOccurrencesResponse, DeleteNotificationOccurrenceRequest, DeleteNotificationOccurrenceResponse, GetNotificationOccurrenceRequest, GetNotificationOccurrenceResponse, ListNotificationOccurrencesRequest, ListNotificationOccurrencesResponse, MarkNotificationReadRequest, MarkNotificationReadResponse, NotificationPolicyServiceGetNotificationPolicyRequest, NotificationPolicyServiceGetNotificationPolicyResponse, NotificationPolicyServiceUpdateNotificationPolicyRequest, NotificationPolicyServiceUpdateNotificationPolicyResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class NotificationService(Protocol):
    """
    Reads, marks read, and deletes notifications for the authenticated viewer.
    """
    async def get_notification_occurrence(self, request: GetNotificationOccurrenceRequest, ctx: RequestContext[GetNotificationOccurrenceRequest, GetNotificationOccurrenceResponse], /) -> GetNotificationOccurrenceResponse:
        """
        Gets one exact visible occurrence. Message-derived occurrences require
        current room membership. Occurrences also require message.read or a
        matching thread relationship with message.read-interactions. Returns NOT_FOUND when the occurrence
        is absent, deleted, expired, or no longer visible to the authenticated
        viewer. Returns UNIMPLEMENTED when this server cannot validate its signal
        kind.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_get_notification_occurrences(self, request: BatchGetNotificationOccurrencesRequest, ctx: RequestContext[BatchGetNotificationOccurrencesRequest, BatchGetNotificationOccurrencesResponse], /) -> BatchGetNotificationOccurrencesResponse:
        """
        Gets an explicit bounded set of visible occurrences. Missing or
        inaccessible IDs are omitted and duplicate IDs are de-duplicated. Returns
        UNIMPLEMENTED rather than partially answering when this server cannot
        validate one requested signal kind.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_notification_occurrences(self, request: ListNotificationOccurrencesRequest, ctx: RequestContext[ListNotificationOccurrencesRequest, ListNotificationOccurrencesResponse], /) -> ListNotificationOccurrencesResponse:
        """
        Lists exact Notifications 2.0 occurrences. Clients may derive temporary
        presentation groups without changing occurrence identity or counts.
        Message-derived occurrences require current room membership. Occurrences
        also require message.read or a matching thread relationship with
        message.read-interactions.
        Returns UNIMPLEMENTED rather than silently omitting an occurrence whose
        signal kind this server version cannot validate and assemble.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def mark_notification_read(self, request: MarkNotificationReadRequest, ctx: RequestContext[MarkNotificationReadRequest, MarkNotificationReadResponse], /) -> MarkNotificationReadResponse:
        """
        Marks one occurrence read. Repeating the call is safe. Returns
        UNIMPLEMENTED when this server cannot validate the occurrence signal kind.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_notification_occurrence(self, request: DeleteNotificationOccurrenceRequest, ctx: RequestContext[DeleteNotificationOccurrenceRequest, DeleteNotificationOccurrenceResponse], /) -> DeleteNotificationOccurrenceResponse:
        """
        Permanently deletes one occurrence while retaining its anti-recreation
        tombstone through the original expiry. Repeating the call is safe. Returns
        UNIMPLEMENTED when this server cannot validate the occurrence signal kind.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_delete_notification_occurrences(self, request: BatchDeleteNotificationOccurrencesRequest, ctx: RequestContext[BatchDeleteNotificationOccurrencesRequest, BatchDeleteNotificationOccurrencesResponse], /) -> BatchDeleteNotificationOccurrencesResponse:
        """
        Permanently deletes an exact set of occurrences. Repeating the call is
        safe because later activity receives different occurrence IDs. Returns
        UNIMPLEMENTED rather than partially deleting a signal kind this server
        cannot validate.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_all_notification_occurrences(self, request: DeleteAllNotificationOccurrencesRequest, ctx: RequestContext[DeleteAllNotificationOccurrencesRequest, DeleteAllNotificationOccurrencesResponse], /) -> DeleteAllNotificationOccurrencesResponse:
        """
        Permanently deletes every visible occurrence current at the server's
        authoritative mutation boundary. Callers must not retry this mutation
        automatically because later activity may arrive after that boundary.
        Returns UNIMPLEMENTED rather than partially deleting a signal kind this
        server cannot validate.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in notifications_pb.desc().services if s.type_name == 'chatto.api.v1.NotificationService')

class NotificationServiceASGIApplication(ConnectASGIApplication[NotificationService]):
    def __init__(
        self,
        service: NotificationService | AsyncGenerator[NotificationService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.NotificationService/GetNotificationOccurrence": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNotificationOccurrence",
                        service_name="chatto.api.v1.NotificationService",
                        input=GetNotificationOccurrenceRequest,
                        output=GetNotificationOccurrenceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_notification_occurrence,
                ),
                "/chatto.api.v1.NotificationService/BatchGetNotificationOccurrences": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=BatchGetNotificationOccurrencesRequest,
                        output=BatchGetNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/ListNotificationOccurrences": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=ListNotificationOccurrencesRequest,
                        output=ListNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/MarkNotificationRead": Endpoint.unary(
                    method=MethodInfo(
                        name="MarkNotificationRead",
                        service_name="chatto.api.v1.NotificationService",
                        input=MarkNotificationReadRequest,
                        output=MarkNotificationReadResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.mark_notification_read,
                ),
                "/chatto.api.v1.NotificationService/DeleteNotificationOccurrence": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteNotificationOccurrence",
                        service_name="chatto.api.v1.NotificationService",
                        input=DeleteNotificationOccurrenceRequest,
                        output=DeleteNotificationOccurrenceResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.delete_notification_occurrence,
                ),
                "/chatto.api.v1.NotificationService/BatchDeleteNotificationOccurrences": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchDeleteNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=BatchDeleteNotificationOccurrencesRequest,
                        output=BatchDeleteNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.batch_delete_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/DeleteAllNotificationOccurrences": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteAllNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=DeleteAllNotificationOccurrencesRequest,
                        output=DeleteAllNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_all_notification_occurrences,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.NotificationService"


class NotificationServiceClient(ConnectClient):
    """
    Reads, marks read, and deletes notifications for the authenticated viewer.
    """
    async def get_notification_occurrence(
        self,
        request: GetNotificationOccurrenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetNotificationOccurrenceResponse:
        """
        Gets one exact visible occurrence. Message-derived occurrences require
        current room membership. Occurrences also require message.read or a
        matching thread relationship with message.read-interactions. Returns NOT_FOUND when the occurrence
        is absent, deleted, expired, or no longer visible to the authenticated
        viewer. Returns UNIMPLEMENTED when this server cannot validate its signal
        kind.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationOccurrence",
                service_name="chatto.api.v1.NotificationService",
                input=GetNotificationOccurrenceRequest,
                output=GetNotificationOccurrenceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_notification_occurrences(
        self,
        request: BatchGetNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetNotificationOccurrencesResponse:
        """
        Gets an explicit bounded set of visible occurrences. Missing or
        inaccessible IDs are omitted and duplicate IDs are de-duplicated. Returns
        UNIMPLEMENTED rather than partially answering when this server cannot
        validate one requested signal kind.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=BatchGetNotificationOccurrencesRequest,
                output=BatchGetNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_notification_occurrences(
        self,
        request: ListNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListNotificationOccurrencesResponse:
        """
        Lists exact Notifications 2.0 occurrences. Clients may derive temporary
        presentation groups without changing occurrence identity or counts.
        Message-derived occurrences require current room membership. Occurrences
        also require message.read or a matching thread relationship with
        message.read-interactions.
        Returns UNIMPLEMENTED rather than silently omitting an occurrence whose
        signal kind this server version cannot validate and assemble.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=ListNotificationOccurrencesRequest,
                output=ListNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def mark_notification_read(
        self,
        request: MarkNotificationReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> MarkNotificationReadResponse:
        """
        Marks one occurrence read. Repeating the call is safe. Returns
        UNIMPLEMENTED when this server cannot validate the occurrence signal kind.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkNotificationRead",
                service_name="chatto.api.v1.NotificationService",
                input=MarkNotificationReadRequest,
                output=MarkNotificationReadResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_notification_occurrence(
        self,
        request: DeleteNotificationOccurrenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteNotificationOccurrenceResponse:
        """
        Permanently deletes one occurrence while retaining its anti-recreation
        tombstone through the original expiry. Repeating the call is safe. Returns
        UNIMPLEMENTED when this server cannot validate the occurrence signal kind.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteNotificationOccurrence",
                service_name="chatto.api.v1.NotificationService",
                input=DeleteNotificationOccurrenceRequest,
                output=DeleteNotificationOccurrenceResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_delete_notification_occurrences(
        self,
        request: BatchDeleteNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchDeleteNotificationOccurrencesResponse:
        """
        Permanently deletes an exact set of occurrences. Repeating the call is
        safe because later activity receives different occurrence IDs. Returns
        UNIMPLEMENTED rather than partially deleting a signal kind this server
        cannot validate.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchDeleteNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=BatchDeleteNotificationOccurrencesRequest,
                output=BatchDeleteNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_all_notification_occurrences(
        self,
        request: DeleteAllNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteAllNotificationOccurrencesResponse:
        """
        Permanently deletes every visible occurrence current at the server's
        authoritative mutation boundary. Callers must not retry this mutation
        automatically because later activity may arrive after that boundary.
        Returns UNIMPLEMENTED rather than partially deleting a signal kind this
        server cannot validate.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAllNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=DeleteAllNotificationOccurrencesRequest,
                output=DeleteAllNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class NotificationServiceSync(Protocol):
    """
    Reads, marks read, and deletes notifications for the authenticated viewer.
    """
    def get_notification_occurrence(self, request: GetNotificationOccurrenceRequest, ctx: RequestContext[GetNotificationOccurrenceRequest, GetNotificationOccurrenceResponse], /) -> GetNotificationOccurrenceResponse:
        """
        Gets one exact visible occurrence. Message-derived occurrences require
        current room membership. Occurrences also require message.read or a
        matching thread relationship with message.read-interactions. Returns NOT_FOUND when the occurrence
        is absent, deleted, expired, or no longer visible to the authenticated
        viewer. Returns UNIMPLEMENTED when this server cannot validate its signal
        kind.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_get_notification_occurrences(self, request: BatchGetNotificationOccurrencesRequest, ctx: RequestContext[BatchGetNotificationOccurrencesRequest, BatchGetNotificationOccurrencesResponse], /) -> BatchGetNotificationOccurrencesResponse:
        """
        Gets an explicit bounded set of visible occurrences. Missing or
        inaccessible IDs are omitted and duplicate IDs are de-duplicated. Returns
        UNIMPLEMENTED rather than partially answering when this server cannot
        validate one requested signal kind.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_notification_occurrences(self, request: ListNotificationOccurrencesRequest, ctx: RequestContext[ListNotificationOccurrencesRequest, ListNotificationOccurrencesResponse], /) -> ListNotificationOccurrencesResponse:
        """
        Lists exact Notifications 2.0 occurrences. Clients may derive temporary
        presentation groups without changing occurrence identity or counts.
        Message-derived occurrences require current room membership. Occurrences
        also require message.read or a matching thread relationship with
        message.read-interactions.
        Returns UNIMPLEMENTED rather than silently omitting an occurrence whose
        signal kind this server version cannot validate and assemble.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def mark_notification_read(self, request: MarkNotificationReadRequest, ctx: RequestContext[MarkNotificationReadRequest, MarkNotificationReadResponse], /) -> MarkNotificationReadResponse:
        """
        Marks one occurrence read. Repeating the call is safe. Returns
        UNIMPLEMENTED when this server cannot validate the occurrence signal kind.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_notification_occurrence(self, request: DeleteNotificationOccurrenceRequest, ctx: RequestContext[DeleteNotificationOccurrenceRequest, DeleteNotificationOccurrenceResponse], /) -> DeleteNotificationOccurrenceResponse:
        """
        Permanently deletes one occurrence while retaining its anti-recreation
        tombstone through the original expiry. Repeating the call is safe. Returns
        UNIMPLEMENTED when this server cannot validate the occurrence signal kind.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_delete_notification_occurrences(self, request: BatchDeleteNotificationOccurrencesRequest, ctx: RequestContext[BatchDeleteNotificationOccurrencesRequest, BatchDeleteNotificationOccurrencesResponse], /) -> BatchDeleteNotificationOccurrencesResponse:
        """
        Permanently deletes an exact set of occurrences. Repeating the call is
        safe because later activity receives different occurrence IDs. Returns
        UNIMPLEMENTED rather than partially deleting a signal kind this server
        cannot validate.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_all_notification_occurrences(self, request: DeleteAllNotificationOccurrencesRequest, ctx: RequestContext[DeleteAllNotificationOccurrencesRequest, DeleteAllNotificationOccurrencesResponse], /) -> DeleteAllNotificationOccurrencesResponse:
        """
        Permanently deletes every visible occurrence current at the server's
        authoritative mutation boundary. Callers must not retry this mutation
        automatically because later activity may arrive after that boundary.
        Returns UNIMPLEMENTED rather than partially deleting a signal kind this
        server cannot validate.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in notifications_pb.desc().services if s.type_name == 'chatto.api.v1.NotificationService')

class NotificationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: NotificationServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.NotificationService/GetNotificationOccurrence": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNotificationOccurrence",
                        service_name="chatto.api.v1.NotificationService",
                        input=GetNotificationOccurrenceRequest,
                        output=GetNotificationOccurrenceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_notification_occurrence,
                ),
                "/chatto.api.v1.NotificationService/BatchGetNotificationOccurrences": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=BatchGetNotificationOccurrencesRequest,
                        output=BatchGetNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/ListNotificationOccurrences": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=ListNotificationOccurrencesRequest,
                        output=ListNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/MarkNotificationRead": EndpointSync.unary(
                    method=MethodInfo(
                        name="MarkNotificationRead",
                        service_name="chatto.api.v1.NotificationService",
                        input=MarkNotificationReadRequest,
                        output=MarkNotificationReadResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.mark_notification_read,
                ),
                "/chatto.api.v1.NotificationService/DeleteNotificationOccurrence": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteNotificationOccurrence",
                        service_name="chatto.api.v1.NotificationService",
                        input=DeleteNotificationOccurrenceRequest,
                        output=DeleteNotificationOccurrenceResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.delete_notification_occurrence,
                ),
                "/chatto.api.v1.NotificationService/BatchDeleteNotificationOccurrences": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchDeleteNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=BatchDeleteNotificationOccurrencesRequest,
                        output=BatchDeleteNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.batch_delete_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/DeleteAllNotificationOccurrences": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteAllNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=DeleteAllNotificationOccurrencesRequest,
                        output=DeleteAllNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_all_notification_occurrences,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.NotificationService"


class NotificationServiceClientSync(ConnectClientSync):
    """
    Reads, marks read, and deletes notifications for the authenticated viewer.
    """
    def get_notification_occurrence(
        self,
        request: GetNotificationOccurrenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetNotificationOccurrenceResponse:
        """
        Gets one exact visible occurrence. Message-derived occurrences require
        current room membership. Occurrences also require message.read or a
        matching thread relationship with message.read-interactions. Returns NOT_FOUND when the occurrence
        is absent, deleted, expired, or no longer visible to the authenticated
        viewer. Returns UNIMPLEMENTED when this server cannot validate its signal
        kind.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationOccurrence",
                service_name="chatto.api.v1.NotificationService",
                input=GetNotificationOccurrenceRequest,
                output=GetNotificationOccurrenceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def batch_get_notification_occurrences(
        self,
        request: BatchGetNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetNotificationOccurrencesResponse:
        """
        Gets an explicit bounded set of visible occurrences. Missing or
        inaccessible IDs are omitted and duplicate IDs are de-duplicated. Returns
        UNIMPLEMENTED rather than partially answering when this server cannot
        validate one requested signal kind.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=BatchGetNotificationOccurrencesRequest,
                output=BatchGetNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_notification_occurrences(
        self,
        request: ListNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListNotificationOccurrencesResponse:
        """
        Lists exact Notifications 2.0 occurrences. Clients may derive temporary
        presentation groups without changing occurrence identity or counts.
        Message-derived occurrences require current room membership. Occurrences
        also require message.read or a matching thread relationship with
        message.read-interactions.
        Returns UNIMPLEMENTED rather than silently omitting an occurrence whose
        signal kind this server version cannot validate and assemble.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=ListNotificationOccurrencesRequest,
                output=ListNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def mark_notification_read(
        self,
        request: MarkNotificationReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> MarkNotificationReadResponse:
        """
        Marks one occurrence read. Repeating the call is safe. Returns
        UNIMPLEMENTED when this server cannot validate the occurrence signal kind.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkNotificationRead",
                service_name="chatto.api.v1.NotificationService",
                input=MarkNotificationReadRequest,
                output=MarkNotificationReadResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_notification_occurrence(
        self,
        request: DeleteNotificationOccurrenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteNotificationOccurrenceResponse:
        """
        Permanently deletes one occurrence while retaining its anti-recreation
        tombstone through the original expiry. Repeating the call is safe. Returns
        UNIMPLEMENTED when this server cannot validate the occurrence signal kind.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteNotificationOccurrence",
                service_name="chatto.api.v1.NotificationService",
                input=DeleteNotificationOccurrenceRequest,
                output=DeleteNotificationOccurrenceResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def batch_delete_notification_occurrences(
        self,
        request: BatchDeleteNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchDeleteNotificationOccurrencesResponse:
        """
        Permanently deletes an exact set of occurrences. Repeating the call is
        safe because later activity receives different occurrence IDs. Returns
        UNIMPLEMENTED rather than partially deleting a signal kind this server
        cannot validate.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchDeleteNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=BatchDeleteNotificationOccurrencesRequest,
                output=BatchDeleteNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_all_notification_occurrences(
        self,
        request: DeleteAllNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteAllNotificationOccurrencesResponse:
        """
        Permanently deletes every visible occurrence current at the server's
        authoritative mutation boundary. Callers must not retry this mutation
        automatically because later activity may arrive after that boundary.
        Returns UNIMPLEMENTED rather than partially deleting a signal kind this
        server cannot validate.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAllNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=DeleteAllNotificationOccurrencesRequest,
                output=DeleteAllNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
class NotificationPolicyService(Protocol):
    """
    Reads and updates the authenticated viewer's server, room-group, and room
    notification delivery policies.
    """
    async def get_notification_policy(self, request: NotificationPolicyServiceGetNotificationPolicyRequest, ctx: RequestContext[NotificationPolicyServiceGetNotificationPolicyRequest, NotificationPolicyServiceGetNotificationPolicyResponse], /) -> NotificationPolicyServiceGetNotificationPolicyResponse:
        """
        Gets explicit and effective modes for one policy scope. Returns NOT_FOUND
        for a missing room group or room, and PERMISSION_DENIED when the viewer is
        not a current member of a requested room.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_get_notification_policies(self, request: BatchGetNotificationPoliciesRequest, ctx: RequestContext[BatchGetNotificationPoliciesRequest, BatchGetNotificationPoliciesResponse], /) -> BatchGetNotificationPoliciesResponse:
        """
        Gets an explicit bounded set of policies. Missing and inaccessible scopes
        are omitted, and duplicate scopes are de-duplicated in first-seen order.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_notification_policy(self, request: NotificationPolicyServiceUpdateNotificationPolicyRequest, ctx: RequestContext[NotificationPolicyServiceUpdateNotificationPolicyRequest, NotificationPolicyServiceUpdateNotificationPolicyResponse], /) -> NotificationPolicyServiceUpdateNotificationPolicyResponse:
        """
        Atomically sets or clears selected overrides at one explicit scope.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in notifications_pb.desc().services if s.type_name == 'chatto.api.v1.NotificationPolicyService')

class NotificationPolicyServiceASGIApplication(ConnectASGIApplication[NotificationPolicyService]):
    def __init__(
        self,
        service: NotificationPolicyService | AsyncGenerator[NotificationPolicyService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.NotificationPolicyService/GetNotificationPolicy": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNotificationPolicy",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=NotificationPolicyServiceGetNotificationPolicyRequest,
                        output=NotificationPolicyServiceGetNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_notification_policy,
                ),
                "/chatto.api.v1.NotificationPolicyService/BatchGetNotificationPolicies": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetNotificationPolicies",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=BatchGetNotificationPoliciesRequest,
                        output=BatchGetNotificationPoliciesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_notification_policies,
                ),
                "/chatto.api.v1.NotificationPolicyService/UpdateNotificationPolicy": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateNotificationPolicy",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=NotificationPolicyServiceUpdateNotificationPolicyRequest,
                        output=NotificationPolicyServiceUpdateNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_notification_policy,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.NotificationPolicyService"


class NotificationPolicyServiceClient(ConnectClient):
    """
    Reads and updates the authenticated viewer's server, room-group, and room
    notification delivery policies.
    """
    async def get_notification_policy(
        self,
        request: NotificationPolicyServiceGetNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> NotificationPolicyServiceGetNotificationPolicyResponse:
        """
        Gets explicit and effective modes for one policy scope. Returns NOT_FOUND
        for a missing room group or room, and PERMISSION_DENIED when the viewer is
        not a current member of a requested room.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationPolicy",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=NotificationPolicyServiceGetNotificationPolicyRequest,
                output=NotificationPolicyServiceGetNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_notification_policies(
        self,
        request: BatchGetNotificationPoliciesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetNotificationPoliciesResponse:
        """
        Gets an explicit bounded set of policies. Missing and inaccessible scopes
        are omitted, and duplicate scopes are de-duplicated in first-seen order.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetNotificationPolicies",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=BatchGetNotificationPoliciesRequest,
                output=BatchGetNotificationPoliciesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_notification_policy(
        self,
        request: NotificationPolicyServiceUpdateNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> NotificationPolicyServiceUpdateNotificationPolicyResponse:
        """
        Atomically sets or clears selected overrides at one explicit scope.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateNotificationPolicy",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=NotificationPolicyServiceUpdateNotificationPolicyRequest,
                output=NotificationPolicyServiceUpdateNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class NotificationPolicyServiceSync(Protocol):
    """
    Reads and updates the authenticated viewer's server, room-group, and room
    notification delivery policies.
    """
    def get_notification_policy(self, request: NotificationPolicyServiceGetNotificationPolicyRequest, ctx: RequestContext[NotificationPolicyServiceGetNotificationPolicyRequest, NotificationPolicyServiceGetNotificationPolicyResponse], /) -> NotificationPolicyServiceGetNotificationPolicyResponse:
        """
        Gets explicit and effective modes for one policy scope. Returns NOT_FOUND
        for a missing room group or room, and PERMISSION_DENIED when the viewer is
        not a current member of a requested room.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_get_notification_policies(self, request: BatchGetNotificationPoliciesRequest, ctx: RequestContext[BatchGetNotificationPoliciesRequest, BatchGetNotificationPoliciesResponse], /) -> BatchGetNotificationPoliciesResponse:
        """
        Gets an explicit bounded set of policies. Missing and inaccessible scopes
        are omitted, and duplicate scopes are de-duplicated in first-seen order.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_notification_policy(self, request: NotificationPolicyServiceUpdateNotificationPolicyRequest, ctx: RequestContext[NotificationPolicyServiceUpdateNotificationPolicyRequest, NotificationPolicyServiceUpdateNotificationPolicyResponse], /) -> NotificationPolicyServiceUpdateNotificationPolicyResponse:
        """
        Atomically sets or clears selected overrides at one explicit scope.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in notifications_pb.desc().services if s.type_name == 'chatto.api.v1.NotificationPolicyService')

class NotificationPolicyServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: NotificationPolicyServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.NotificationPolicyService/GetNotificationPolicy": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNotificationPolicy",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=NotificationPolicyServiceGetNotificationPolicyRequest,
                        output=NotificationPolicyServiceGetNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_notification_policy,
                ),
                "/chatto.api.v1.NotificationPolicyService/BatchGetNotificationPolicies": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetNotificationPolicies",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=BatchGetNotificationPoliciesRequest,
                        output=BatchGetNotificationPoliciesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_notification_policies,
                ),
                "/chatto.api.v1.NotificationPolicyService/UpdateNotificationPolicy": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateNotificationPolicy",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=NotificationPolicyServiceUpdateNotificationPolicyRequest,
                        output=NotificationPolicyServiceUpdateNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_notification_policy,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.NotificationPolicyService"


class NotificationPolicyServiceClientSync(ConnectClientSync):
    """
    Reads and updates the authenticated viewer's server, room-group, and room
    notification delivery policies.
    """
    def get_notification_policy(
        self,
        request: NotificationPolicyServiceGetNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> NotificationPolicyServiceGetNotificationPolicyResponse:
        """
        Gets explicit and effective modes for one policy scope. Returns NOT_FOUND
        for a missing room group or room, and PERMISSION_DENIED when the viewer is
        not a current member of a requested room.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationPolicy",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=NotificationPolicyServiceGetNotificationPolicyRequest,
                output=NotificationPolicyServiceGetNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def batch_get_notification_policies(
        self,
        request: BatchGetNotificationPoliciesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetNotificationPoliciesResponse:
        """
        Gets an explicit bounded set of policies. Missing and inaccessible scopes
        are omitted, and duplicate scopes are de-duplicated in first-seen order.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetNotificationPolicies",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=BatchGetNotificationPoliciesRequest,
                output=BatchGetNotificationPoliciesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def update_notification_policy(
        self,
        request: NotificationPolicyServiceUpdateNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> NotificationPolicyServiceUpdateNotificationPolicyResponse:
        """
        Atomically sets or clears selected overrides at one explicit scope.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateNotificationPolicy",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=NotificationPolicyServiceUpdateNotificationPolicyRequest,
                output=NotificationPolicyServiceUpdateNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
