# Generated from chatto/api/v1/pagination.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.2.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from ....buf.validate import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile


_PageRequestFields: TypeAlias = Literal["limit", "offset"]

class PageRequest(Message[_PageRequestFields]):
    """
    Offset-based page request for list RPCs whose result order is stable enough
    for simple list browsing.

    ```proto
    message chatto.api.v1.PageRequest
    ```

    Attributes:
        limit:
            Maximum number of items to request. Each RPC defines its default and
            effective maximum; this shared request shape accepts values up to 500.

            ```proto
            int32 limit = 1;
            ```
        offset:
            Zero-based number of matching items to skip.

            ```proto
            int32 offset = 2;
            ```
    """

    __slots__ = ("limit", "offset")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            limit: int = 0,
            offset: int = 0,
        ) -> None:
            pass

        limit: int
        offset: int

_PageInfoFields: TypeAlias = Literal["total_count", "has_more"]

class PageInfo(Message[_PageInfoFields]):
    """
    Offset-based page metadata returned by list RPCs.

    ```proto
    message chatto.api.v1.PageInfo
    ```

    Attributes:
        total_count:
            Total matching item count before pagination.

            ```proto
            int64 total_count = 1;
            ```
        has_more:
            True when another page exists after this response.

            ```proto
            bool has_more = 2;
            ```
    """

    __slots__ = ("total_count", "has_more")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            total_count: int = 0,
            has_more: bool = False,
        ) -> None:
            pass

        total_count: int
        has_more: bool


_DESC = file_desc(
    b'\n\x1echatto/api/v1/pagination.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto"P\n\x0bPageRequest\x12 \n\x05limit\x18\x01 \x01(\x05R\x05limitB\n\xbaH\x07\x1a\x05\x18\xf4\x03(\x00\x12\x1f\n\x06offset\x18\x02 \x01(\x05R\x06offsetB\x07\xbaH\x04\x1a\x02(\x00"F\n\x08PageInfo\x12\x1f\n\x0btotal_count\x18\x01 \x01(\x03R\ntotalCount\x12\x19\n\x08has_more\x18\x02 \x01(\x08R\x07hasMoreBz\n\x11com.chatto.api.v1B\x0fPaginationProtoP\x01\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3',
    [
        validate_pb.desc(),
    ],
    {
        "PageRequest": PageRequest,
        "PageInfo": PageInfo,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `chatto/api/v1/pagination.proto`."""
    return _DESC
