# Generated from chatto/api/v1/push_notifications.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.2.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from ....buf.validate import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile


_SubscribePushRequestFields: TypeAlias = Literal["endpoint", "p256dh", "auth", "user_agent"]

class SubscribePushRequest(Message[_SubscribePushRequestFields]):
    """
    Request to store a PushSubscription returned by the browser Push API.

    ```proto
    message chatto.api.v1.SubscribePushRequest
    ```

    Attributes:
        endpoint:
            Push service endpoint URL.

            ```proto
            string endpoint = 1;
            ```
        p256dh:
            Client P-256 ECDH public key from PushSubscription.keys.p256dh.

            ```proto
            string p256dh = 2;
            ```
        auth:
            Authentication secret from PushSubscription.keys.auth.

            ```proto
            string auth = 3;
            ```
        user_agent:
            Optional browser user-agent string for device identification.

            ```proto
            optional string user_agent = 4;
            ```
    """

    __slots__ = ("endpoint", "p256dh", "auth", "user_agent")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            endpoint: str = "",
            p256dh: str = "",
            auth: str = "",
            user_agent: str | None = None,
        ) -> None:
            pass

        endpoint: str
        p256dh: str
        auth: str
        user_agent: str

_SubscribePushResponseFields: TypeAlias = Literal["subscribed"]

class SubscribePushResponse(Message[_SubscribePushResponseFields]):
    """
    Response from storing a browser push subscription.

    ```proto
    message chatto.api.v1.SubscribePushResponse
    ```

    Attributes:
        subscribed:
            True when the subscription was stored.

            ```proto
            bool subscribed = 1;
            ```
    """

    __slots__ = ("subscribed",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            subscribed: bool = False,
        ) -> None:
            pass

        subscribed: bool

_UnsubscribePushRequestFields: TypeAlias = Literal["endpoint"]

class UnsubscribePushRequest(Message[_UnsubscribePushRequestFields]):
    """
    Request to remove a browser push subscription.

    ```proto
    message chatto.api.v1.UnsubscribePushRequest
    ```

    Attributes:
        endpoint:
            Push service endpoint URL to remove.

            ```proto
            string endpoint = 1;
            ```
    """

    __slots__ = ("endpoint",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            endpoint: str = "",
        ) -> None:
            pass

        endpoint: str

_UnsubscribePushResponseFields: TypeAlias = Literal["unsubscribed"]

class UnsubscribePushResponse(Message[_UnsubscribePushResponseFields]):
    """
    Response from removing a browser push subscription.

    ```proto
    message chatto.api.v1.UnsubscribePushResponse
    ```

    Attributes:
        unsubscribed:
            True when the request completed.

            ```proto
            bool unsubscribed = 1;
            ```
    """

    __slots__ = ("unsubscribed",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            unsubscribed: bool = False,
        ) -> None:
            pass

        unsubscribed: bool

_SendTestPushNotificationRequestFields: TypeAlias = NoReturn

class SendTestPushNotificationRequest(Message[_SendTestPushNotificationRequestFields]):
    """
    Request to test the current user's registered browser push subscriptions.

    ```proto
    message chatto.api.v1.SendTestPushNotificationRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_SendTestPushNotificationResponseFields: TypeAlias = Literal["sent"]

class SendTestPushNotificationResponse(Message[_SendTestPushNotificationResponseFields]):
    """
    Result of sending a test Web Push notification.

    ```proto
    message chatto.api.v1.SendTestPushNotificationResponse
    ```

    Attributes:
        sent:
            True when the push provider accepted the notification.

            ```proto
            bool sent = 1;
            ```
    """

    __slots__ = ("sent",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            sent: bool = False,
        ) -> None:
            pass

        sent: bool


_DESC = file_desc(
    b'\n&chatto/api/v1/push_notifications.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto"\xbf\x01\n\x14SubscribePushRequest\x12&\n\x08endpoint\x18\x01 \x01(\tR\x08endpointB\n\xbaH\x07r\x05\x10\x01\x18\x80 \x12"\n\x06p256dh\x18\x02 \x01(\tR\x06p256dhB\n\xbaH\x07r\x05\x10\x01\x18\x80\x02\x12\x1e\n\x04auth\x18\x03 \x01(\tR\x04authB\n\xbaH\x07r\x05\x10\x01\x18\x80\x01\x12,\n\nuser_agent\x18\x04 \x01(\tH\x00R\tuserAgentB\x08\xbaH\x05r\x03\x18\x80\x04\x88\x01\x01B\r\n\x0b_user_agent"7\n\x15SubscribePushResponse\x12\x1e\n\nsubscribed\x18\x01 \x01(\x08R\nsubscribed"@\n\x16UnsubscribePushRequest\x12&\n\x08endpoint\x18\x01 \x01(\tR\x08endpointB\n\xbaH\x07r\x05\x10\x01\x18\x80 "=\n\x17UnsubscribePushResponse\x12"\n\x0cunsubscribed\x18\x01 \x01(\x08R\x0cunsubscribed"!\n\x1fSendTestPushNotificationRequest"6\n SendTestPushNotificationResponse\x12\x12\n\x04sent\x18\x01 \x01(\x08R\x04sent2\xcd\x02\n\x17PushNotificationService\x12V\n\tSubscribe\x12#.chatto.api.v1.SubscribePushRequest\x1a$.chatto.api.v1.SubscribePushResponse\x12a\n\x0bUnsubscribe\x12%.chatto.api.v1.UnsubscribePushRequest\x1a&.chatto.api.v1.UnsubscribePushResponse"\x03\x90\x02\x02\x12w\n\x14SendTestNotification\x12..chatto.api.v1.SendTestPushNotificationRequest\x1a/.chatto.api.v1.SendTestPushNotificationResponseB\x81\x01\n\x11com.chatto.api.v1B\x16PushNotificationsProtoP\x01\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3',
    [
        validate_pb.desc(),
    ],
    {
        "SubscribePushRequest": SubscribePushRequest,
        "SubscribePushResponse": SubscribePushResponse,
        "UnsubscribePushRequest": UnsubscribePushRequest,
        "UnsubscribePushResponse": UnsubscribePushResponse,
        "SendTestPushNotificationRequest": SendTestPushNotificationRequest,
        "SendTestPushNotificationResponse": SendTestPushNotificationResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `chatto/api/v1/push_notifications.proto`."""
    return _DESC
