# Generated from chatto/api/v1/room_directory.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import room_directory_pb
from .room_directory_pb import BatchGetRoomGroupsRequest, BatchGetRoomGroupsResponse, BatchGetRoomsRequest, BatchGetRoomsResponse, GetRoomGroupRequest, GetRoomGroupResponse, GetRoomRequest, GetRoomResponse, ListRoomGroupsRequest, ListRoomGroupsResponse, ListRoomsRequest, ListRoomsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class RoomDirectoryService(Protocol):
    """
    Reads room directory data.
    """
    async def list_rooms(self, request: ListRoomsRequest, ctx: RequestContext[ListRoomsRequest, ListRoomsResponse], /) -> ListRoomsResponse:
        """
        Lists rooms visible to the current user. Defaults to active rooms; use
        archive_filter to discover archived rooms or include both states. Channel
        rooms require membership or room.list. DM membership exposes room and
        participant metadata. Message-derived DM state also requires current
        read permission. Accessible empty DMs are included. Returns up to 100 rooms
        ordered by ID ascending; the default page size is 50.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_room_groups(self, request: ListRoomGroupsRequest, ctx: RequestContext[ListRoomGroupsRequest, ListRoomGroupsResponse], /) -> ListRoomGroupsResponse:
        """
        Lists ordered channel room groups and sidebar items visible to the current
        user as a finite navigation snapshot. Hidden room entries are omitted.
        Archived room entries are omitted.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_room_group(self, request: GetRoomGroupRequest, ctx: RequestContext[GetRoomGroupRequest, GetRoomGroupResponse], /) -> GetRoomGroupResponse:
        """
        Returns one ordered room group by ID. Hidden room entries are omitted.
        Archived room entries are omitted.
        Returns NOT_FOUND when the room group does not exist.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_get_room_groups(self, request: BatchGetRoomGroupsRequest, ctx: RequestContext[BatchGetRoomGroupsRequest, BatchGetRoomGroupsResponse], /) -> BatchGetRoomGroupsResponse:
        """
        Returns ordered room groups for a set of stable group IDs. Hidden room
        entries are omitted. Archived room entries are omitted. Unknown groups are
        omitted. Results preserve first-seen request order and repeated IDs are
        de-duplicated.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_room(self, request: GetRoomRequest, ctx: RequestContext[GetRoomRequest, GetRoomResponse], /) -> GetRoomResponse:
        """
        Returns one visible room by ID. DM rooms require membership. Returns
        NOT_FOUND when the room does not exist and PERMISSION_DENIED when the room
        exists but is hidden from the caller.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_get_rooms(self, request: BatchGetRoomsRequest, ctx: RequestContext[BatchGetRoomsRequest, BatchGetRoomsResponse], /) -> BatchGetRoomsResponse:
        """
        Returns visible rooms for a set of stable room IDs. This is a direct
        hydration API, so visible archived rooms may be returned. Unknown rooms and
        rooms hidden from the caller are omitted. Results preserve first-seen
        request order and repeated IDs are de-duplicated.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in room_directory_pb.desc().services if s.type_name == 'chatto.api.v1.RoomDirectoryService')

class RoomDirectoryServiceASGIApplication(ConnectASGIApplication[RoomDirectoryService]):
    def __init__(
        self,
        service: RoomDirectoryService | AsyncGenerator[RoomDirectoryService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.RoomDirectoryService/ListRooms": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRooms",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=ListRoomsRequest,
                        output=ListRoomsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_rooms,
                ),
                "/chatto.api.v1.RoomDirectoryService/ListRoomGroups": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRoomGroups",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=ListRoomGroupsRequest,
                        output=ListRoomGroupsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_room_groups,
                ),
                "/chatto.api.v1.RoomDirectoryService/GetRoomGroup": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRoomGroup",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=GetRoomGroupRequest,
                        output=GetRoomGroupResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_room_group,
                ),
                "/chatto.api.v1.RoomDirectoryService/BatchGetRoomGroups": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetRoomGroups",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=BatchGetRoomGroupsRequest,
                        output=BatchGetRoomGroupsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_room_groups,
                ),
                "/chatto.api.v1.RoomDirectoryService/GetRoom": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRoom",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=GetRoomRequest,
                        output=GetRoomResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_room,
                ),
                "/chatto.api.v1.RoomDirectoryService/BatchGetRooms": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetRooms",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=BatchGetRoomsRequest,
                        output=BatchGetRoomsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_rooms,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.RoomDirectoryService"


class RoomDirectoryServiceClient(ConnectClient):
    """
    Reads room directory data.
    """
    async def list_rooms(
        self,
        request: ListRoomsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListRoomsResponse:
        """
        Lists rooms visible to the current user. Defaults to active rooms; use
        archive_filter to discover archived rooms or include both states. Channel
        rooms require membership or room.list. DM membership exposes room and
        participant metadata. Message-derived DM state also requires current
        read permission. Accessible empty DMs are included. Returns up to 100 rooms
        ordered by ID ascending; the default page size is 50.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRooms",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=ListRoomsRequest,
                output=ListRoomsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_room_groups(
        self,
        request: ListRoomGroupsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListRoomGroupsResponse:
        """
        Lists ordered channel room groups and sidebar items visible to the current
        user as a finite navigation snapshot. Hidden room entries are omitted.
        Archived room entries are omitted.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRoomGroups",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=ListRoomGroupsRequest,
                output=ListRoomGroupsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_room_group(
        self,
        request: GetRoomGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetRoomGroupResponse:
        """
        Returns one ordered room group by ID. Hidden room entries are omitted.
        Archived room entries are omitted.
        Returns NOT_FOUND when the room group does not exist.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRoomGroup",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=GetRoomGroupRequest,
                output=GetRoomGroupResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_room_groups(
        self,
        request: BatchGetRoomGroupsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetRoomGroupsResponse:
        """
        Returns ordered room groups for a set of stable group IDs. Hidden room
        entries are omitted. Archived room entries are omitted. Unknown groups are
        omitted. Results preserve first-seen request order and repeated IDs are
        de-duplicated.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetRoomGroups",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=BatchGetRoomGroupsRequest,
                output=BatchGetRoomGroupsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_room(
        self,
        request: GetRoomRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetRoomResponse:
        """
        Returns one visible room by ID. DM rooms require membership. Returns
        NOT_FOUND when the room does not exist and PERMISSION_DENIED when the room
        exists but is hidden from the caller.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRoom",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=GetRoomRequest,
                output=GetRoomResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_rooms(
        self,
        request: BatchGetRoomsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetRoomsResponse:
        """
        Returns visible rooms for a set of stable room IDs. This is a direct
        hydration API, so visible archived rooms may be returned. Unknown rooms and
        rooms hidden from the caller are omitted. Results preserve first-seen
        request order and repeated IDs are de-duplicated.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetRooms",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=BatchGetRoomsRequest,
                output=BatchGetRoomsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class RoomDirectoryServiceSync(Protocol):
    """
    Reads room directory data.
    """
    def list_rooms(self, request: ListRoomsRequest, ctx: RequestContext[ListRoomsRequest, ListRoomsResponse], /) -> ListRoomsResponse:
        """
        Lists rooms visible to the current user. Defaults to active rooms; use
        archive_filter to discover archived rooms or include both states. Channel
        rooms require membership or room.list. DM membership exposes room and
        participant metadata. Message-derived DM state also requires current
        read permission. Accessible empty DMs are included. Returns up to 100 rooms
        ordered by ID ascending; the default page size is 50.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_room_groups(self, request: ListRoomGroupsRequest, ctx: RequestContext[ListRoomGroupsRequest, ListRoomGroupsResponse], /) -> ListRoomGroupsResponse:
        """
        Lists ordered channel room groups and sidebar items visible to the current
        user as a finite navigation snapshot. Hidden room entries are omitted.
        Archived room entries are omitted.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_room_group(self, request: GetRoomGroupRequest, ctx: RequestContext[GetRoomGroupRequest, GetRoomGroupResponse], /) -> GetRoomGroupResponse:
        """
        Returns one ordered room group by ID. Hidden room entries are omitted.
        Archived room entries are omitted.
        Returns NOT_FOUND when the room group does not exist.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_get_room_groups(self, request: BatchGetRoomGroupsRequest, ctx: RequestContext[BatchGetRoomGroupsRequest, BatchGetRoomGroupsResponse], /) -> BatchGetRoomGroupsResponse:
        """
        Returns ordered room groups for a set of stable group IDs. Hidden room
        entries are omitted. Archived room entries are omitted. Unknown groups are
        omitted. Results preserve first-seen request order and repeated IDs are
        de-duplicated.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_room(self, request: GetRoomRequest, ctx: RequestContext[GetRoomRequest, GetRoomResponse], /) -> GetRoomResponse:
        """
        Returns one visible room by ID. DM rooms require membership. Returns
        NOT_FOUND when the room does not exist and PERMISSION_DENIED when the room
        exists but is hidden from the caller.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_get_rooms(self, request: BatchGetRoomsRequest, ctx: RequestContext[BatchGetRoomsRequest, BatchGetRoomsResponse], /) -> BatchGetRoomsResponse:
        """
        Returns visible rooms for a set of stable room IDs. This is a direct
        hydration API, so visible archived rooms may be returned. Unknown rooms and
        rooms hidden from the caller are omitted. Results preserve first-seen
        request order and repeated IDs are de-duplicated.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in room_directory_pb.desc().services if s.type_name == 'chatto.api.v1.RoomDirectoryService')

class RoomDirectoryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: RoomDirectoryServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.RoomDirectoryService/ListRooms": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRooms",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=ListRoomsRequest,
                        output=ListRoomsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_rooms,
                ),
                "/chatto.api.v1.RoomDirectoryService/ListRoomGroups": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRoomGroups",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=ListRoomGroupsRequest,
                        output=ListRoomGroupsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_room_groups,
                ),
                "/chatto.api.v1.RoomDirectoryService/GetRoomGroup": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRoomGroup",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=GetRoomGroupRequest,
                        output=GetRoomGroupResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_room_group,
                ),
                "/chatto.api.v1.RoomDirectoryService/BatchGetRoomGroups": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetRoomGroups",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=BatchGetRoomGroupsRequest,
                        output=BatchGetRoomGroupsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_room_groups,
                ),
                "/chatto.api.v1.RoomDirectoryService/GetRoom": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRoom",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=GetRoomRequest,
                        output=GetRoomResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_room,
                ),
                "/chatto.api.v1.RoomDirectoryService/BatchGetRooms": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetRooms",
                        service_name="chatto.api.v1.RoomDirectoryService",
                        input=BatchGetRoomsRequest,
                        output=BatchGetRoomsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_rooms,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.RoomDirectoryService"


class RoomDirectoryServiceClientSync(ConnectClientSync):
    """
    Reads room directory data.
    """
    def list_rooms(
        self,
        request: ListRoomsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListRoomsResponse:
        """
        Lists rooms visible to the current user. Defaults to active rooms; use
        archive_filter to discover archived rooms or include both states. Channel
        rooms require membership or room.list. DM membership exposes room and
        participant metadata. Message-derived DM state also requires current
        read permission. Accessible empty DMs are included. Returns up to 100 rooms
        ordered by ID ascending; the default page size is 50.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRooms",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=ListRoomsRequest,
                output=ListRoomsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_room_groups(
        self,
        request: ListRoomGroupsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListRoomGroupsResponse:
        """
        Lists ordered channel room groups and sidebar items visible to the current
        user as a finite navigation snapshot. Hidden room entries are omitted.
        Archived room entries are omitted.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRoomGroups",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=ListRoomGroupsRequest,
                output=ListRoomGroupsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_room_group(
        self,
        request: GetRoomGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetRoomGroupResponse:
        """
        Returns one ordered room group by ID. Hidden room entries are omitted.
        Archived room entries are omitted.
        Returns NOT_FOUND when the room group does not exist.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRoomGroup",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=GetRoomGroupRequest,
                output=GetRoomGroupResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def batch_get_room_groups(
        self,
        request: BatchGetRoomGroupsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetRoomGroupsResponse:
        """
        Returns ordered room groups for a set of stable group IDs. Hidden room
        entries are omitted. Archived room entries are omitted. Unknown groups are
        omitted. Results preserve first-seen request order and repeated IDs are
        de-duplicated.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetRoomGroups",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=BatchGetRoomGroupsRequest,
                output=BatchGetRoomGroupsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_room(
        self,
        request: GetRoomRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetRoomResponse:
        """
        Returns one visible room by ID. DM rooms require membership. Returns
        NOT_FOUND when the room does not exist and PERMISSION_DENIED when the room
        exists but is hidden from the caller.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRoom",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=GetRoomRequest,
                output=GetRoomResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def batch_get_rooms(
        self,
        request: BatchGetRoomsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetRoomsResponse:
        """
        Returns visible rooms for a set of stable room IDs. This is a direct
        hydration API, so visible archived rooms may be returned. Unknown rooms and
        rooms hidden from the caller are omitted. Results preserve first-seen
        request order and repeated IDs are de-duplicated.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetRooms",
                service_name="chatto.api.v1.RoomDirectoryService",
                input=BatchGetRoomsRequest,
                output=BatchGetRoomsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
