# Generated from chatto/api/v1/server.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from . import common_pb

if TYPE_CHECKING:
    from protobuf import DescFile

    from .common_pb import ProviderMetadata


_ServerPublicProfileFields: TypeAlias = Literal["name", "version", "logo_url", "banner_url", "welcome_message", "description"]

class ServerPublicProfile(Message[_ServerPublicProfileFields]):
    """
    Public server profile, identity, and branding fields.

    ```proto
    message chatto.api.v1.ServerPublicProfile
    ```

    Attributes:
        name:
            Display name of the Chatto server.

            ```proto
            string name = 1;
            ```
        version:
            Server software version.

            ```proto
            string version = 2;
            ```
        logo_url:
            Optional server logo URL.

            ```proto
            optional string logo_url = 3;
            ```
        banner_url:
            Optional server banner URL.

            ```proto
            optional string banner_url = 4;
            ```
        welcome_message:
            Optional welcome message.

            ```proto
            optional string welcome_message = 5;
            ```
        description:
            Optional server description.

            ```proto
            optional string description = 6;
            ```
    """

    __slots__ = ("name", "version", "logo_url", "banner_url", "welcome_message", "description")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            name: str = "",
            version: str = "",
            logo_url: str | None = None,
            banner_url: str | None = None,
            welcome_message: str | None = None,
            description: str | None = None,
        ) -> None:
            pass

        name: str
        version: str
        logo_url: str
        banner_url: str
        welcome_message: str
        description: str

_ServerLoginFields: TypeAlias = Literal["direct_registration_enabled", "providers", "authorize_url"]

class ServerLogin(Message[_ServerLoginFields]):
    """
    Login and registration options exposed before authentication.

    ```proto
    message chatto.api.v1.ServerLogin
    ```

    Attributes:
        direct_registration_enabled:
            Whether users can create accounts through the public UI.

            ```proto
            bool direct_registration_enabled = 1;
            ```
        providers:
            Configured login providers.

            ```proto
            repeated chatto.api.v1.ProviderMetadata providers = 2;
            ```
        authorize_url:
            URL for the legacy authorization flow, when enabled.

            ```proto
            string authorize_url = 3;
            ```
    """

    __slots__ = ("direct_registration_enabled", "providers", "authorize_url")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            direct_registration_enabled: bool = False,
            providers: list[ProviderMetadata] | None = None,
            authorize_url: str = "",
        ) -> None:
            pass

        direct_registration_enabled: bool
        providers: list[ProviderMetadata]
        authorize_url: str


_DESC = file_desc(
    b'\n\x1achatto/api/v1/server.proto\x12\rchatto.api.v1\x1a\x1achatto/api/v1/common.proto"\x9c\x02\n\x13ServerPublicProfile\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version\x12\x1e\n\x08logo_url\x18\x03 \x01(\tH\x00R\x07logoUrl\x88\x01\x01\x12"\n\nbanner_url\x18\x04 \x01(\tH\x01R\tbannerUrl\x88\x01\x01\x12,\n\x0fwelcome_message\x18\x05 \x01(\tH\x02R\x0ewelcomeMessage\x88\x01\x01\x12%\n\x0bdescription\x18\x06 \x01(\tH\x03R\x0bdescription\x88\x01\x01B\x0b\n\t_logo_urlB\r\n\x0b_banner_urlB\x12\n\x10_welcome_messageB\x0e\n\x0c_description"\xb1\x01\n\x0bServerLogin\x12>\n\x1bdirect_registration_enabled\x18\x01 \x01(\x08R\x19directRegistrationEnabled\x12=\n\tproviders\x18\x02 \x03(\x0b2\x1f.chatto.api.v1.ProviderMetadataR\tproviders\x12#\n\rauthorize_url\x18\x03 \x01(\tR\x0cauthorizeUrlBv\n\x11com.chatto.api.v1B\x0bServerProtoP\x01\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3',
    [
        common_pb.desc(),
    ],
    {
        "ServerPublicProfile": ServerPublicProfile,
        "ServerLogin": ServerLogin,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `chatto/api/v1/server.proto`."""
    return _DESC
