# Generated from chatto/api/v1/threads.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import threads_pb
from .read_state_pb import BatchGetThreadReadStatesRequest, BatchGetThreadReadStatesResponse, GetThreadReadStateRequest, GetThreadReadStateResponse, MarkThreadAsReadRequest, MarkThreadAsReadResponse
from .room_timeline_pb import GetThreadEventsAroundRequest, GetThreadEventsAroundResponse, GetThreadEventsRequest, GetThreadEventsResponse
from .threads_pb import FollowThreadRequest, FollowThreadResponse, ListFollowedThreadsRequest, ListFollowedThreadsResponse, ListThreadParticipantsRequest, ListThreadParticipantsResponse, UnfollowThreadRequest, UnfollowThreadResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class ThreadService(Protocol):
    """
    Manages thread follow state for the current user.
    """
    async def get_thread_read_state(self, request: GetThreadReadStateRequest, ctx: RequestContext[GetThreadReadStateRequest, GetThreadReadStateResponse], /) -> GetThreadReadStateResponse:
        """
        Reads the current viewer's stored marker without changing it. Requires the
        same membership and read access as MarkThreadAsRead. Missing resources
        return NOT_FOUND; inaccessible resources return PERMISSION_DENIED.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_get_thread_read_states(self, request: BatchGetThreadReadStatesRequest, ctx: RequestContext[BatchGetThreadReadStatesRequest, BatchGetThreadReadStatesResponse], /) -> BatchGetThreadReadStatesResponse:
        """
        Reads up to 100 states under the same authorization as GetThreadReadState.
        Missing and inaccessible resources are omitted; duplicates use first-seen order.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_thread_participants(self, request: ListThreadParticipantsRequest, ctx: RequestContext[ListThreadParticipantsRequest, ListThreadParticipantsResponse], /) -> ListThreadParticipantsResponse:
        """
        Lists distinct authors of non-retracted replies, excluding erased users.
        The root author is included only if they also replied. Requires the same
        membership and message-read access as GetThreadEvents.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_followed_threads(self, request: ListFollowedThreadsRequest, ctx: RequestContext[ListFollowedThreadsRequest, ListFollowedThreadsResponse], /) -> ListFollowedThreadsResponse:
        """
        Returns followed threads in rooms where the current user is a member.
        All threads also require message.read or an active relationship with
        message.read-interactions. Direct-message threads are returned only when
        include_direct_message_threads is true.
        The result includes enough root and latest-reply data for clients to render
        the list without extra per-thread fetches.
        Activity can reorder the live result between offset pages. After a thread
        activity update, clients must restart paging at offset zero.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def follow_thread(self, request: FollowThreadRequest, ctx: RequestContext[FollowThreadRequest, FollowThreadResponse], /) -> FollowThreadResponse:
        """
        Follows a thread for the current user. Room membership plus message.read or
        an active relationship with message.read-interactions are required.
        Followed threads can be surfaced in clients and can participate in thread
        notification behavior.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def unfollow_thread(self, request: UnfollowThreadRequest, ctx: RequestContext[UnfollowThreadRequest, UnfollowThreadResponse], /) -> UnfollowThreadResponse:
        """
        Stops following a thread for the current user. Room membership plus
        message.read or an active relationship with message.read-interactions are
        required. The response reports
        the resulting follow state so clients can update local UI immediately.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_thread_events(self, request: GetThreadEventsRequest, ctx: RequestContext[GetThreadEventsRequest, GetThreadEventsResponse], /) -> GetThreadEventsResponse:
        """
        Returns one page of events in a message thread. Room membership is
        required. Reads also require message.read or an active relationship with
        message.read-interactions. Initial pages include the thread root message; cursor pages
        return replies in the requested direction.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_thread_events_around(self, request: GetThreadEventsAroundRequest, ctx: RequestContext[GetThreadEventsAroundRequest, GetThreadEventsAroundResponse], /) -> GetThreadEventsAroundResponse:
        """
        Returns a thread timeline window centered around a specific event. Use this
        to open a reply from a notification or search result in context. Returns
        NOT_FOUND when the thread root or anchor event is missing or hidden.
        Returns PERMISSION_DENIED when room membership is missing, both read modes
        are missing, or an interaction-scoped account has no relationship with the
        thread.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def mark_thread_as_read(self, request: MarkThreadAsReadRequest, ctx: RequestContext[MarkThreadAsReadRequest, MarkThreadAsReadResponse], /) -> MarkThreadAsReadResponse:
        """
        Marks a thread timeline as read through the supplied event without changing
        the room-level read marker. Room membership plus message.read or an active
        relationship with message.read-interactions are required.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in threads_pb.desc().services if s.type_name == 'chatto.api.v1.ThreadService')

class ThreadServiceASGIApplication(ConnectASGIApplication[ThreadService]):
    def __init__(
        self,
        service: ThreadService | AsyncGenerator[ThreadService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.ThreadService/GetThreadReadState": Endpoint.unary(
                    method=MethodInfo(
                        name="GetThreadReadState",
                        service_name="chatto.api.v1.ThreadService",
                        input=GetThreadReadStateRequest,
                        output=GetThreadReadStateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_thread_read_state,
                ),
                "/chatto.api.v1.ThreadService/BatchGetThreadReadStates": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetThreadReadStates",
                        service_name="chatto.api.v1.ThreadService",
                        input=BatchGetThreadReadStatesRequest,
                        output=BatchGetThreadReadStatesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_thread_read_states,
                ),
                "/chatto.api.v1.ThreadService/ListThreadParticipants": Endpoint.unary(
                    method=MethodInfo(
                        name="ListThreadParticipants",
                        service_name="chatto.api.v1.ThreadService",
                        input=ListThreadParticipantsRequest,
                        output=ListThreadParticipantsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_thread_participants,
                ),
                "/chatto.api.v1.ThreadService/ListFollowedThreads": Endpoint.unary(
                    method=MethodInfo(
                        name="ListFollowedThreads",
                        service_name="chatto.api.v1.ThreadService",
                        input=ListFollowedThreadsRequest,
                        output=ListFollowedThreadsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_followed_threads,
                ),
                "/chatto.api.v1.ThreadService/FollowThread": Endpoint.unary(
                    method=MethodInfo(
                        name="FollowThread",
                        service_name="chatto.api.v1.ThreadService",
                        input=FollowThreadRequest,
                        output=FollowThreadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.follow_thread,
                ),
                "/chatto.api.v1.ThreadService/UnfollowThread": Endpoint.unary(
                    method=MethodInfo(
                        name="UnfollowThread",
                        service_name="chatto.api.v1.ThreadService",
                        input=UnfollowThreadRequest,
                        output=UnfollowThreadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.unfollow_thread,
                ),
                "/chatto.api.v1.ThreadService/GetThreadEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="GetThreadEvents",
                        service_name="chatto.api.v1.ThreadService",
                        input=GetThreadEventsRequest,
                        output=GetThreadEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_thread_events,
                ),
                "/chatto.api.v1.ThreadService/GetThreadEventsAround": Endpoint.unary(
                    method=MethodInfo(
                        name="GetThreadEventsAround",
                        service_name="chatto.api.v1.ThreadService",
                        input=GetThreadEventsAroundRequest,
                        output=GetThreadEventsAroundResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_thread_events_around,
                ),
                "/chatto.api.v1.ThreadService/MarkThreadAsRead": Endpoint.unary(
                    method=MethodInfo(
                        name="MarkThreadAsRead",
                        service_name="chatto.api.v1.ThreadService",
                        input=MarkThreadAsReadRequest,
                        output=MarkThreadAsReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.mark_thread_as_read,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.ThreadService"


class ThreadServiceClient(ConnectClient):
    """
    Manages thread follow state for the current user.
    """
    async def get_thread_read_state(
        self,
        request: GetThreadReadStateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetThreadReadStateResponse:
        """
        Reads the current viewer's stored marker without changing it. Requires the
        same membership and read access as MarkThreadAsRead. Missing resources
        return NOT_FOUND; inaccessible resources return PERMISSION_DENIED.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadReadState",
                service_name="chatto.api.v1.ThreadService",
                input=GetThreadReadStateRequest,
                output=GetThreadReadStateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_thread_read_states(
        self,
        request: BatchGetThreadReadStatesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetThreadReadStatesResponse:
        """
        Reads up to 100 states under the same authorization as GetThreadReadState.
        Missing and inaccessible resources are omitted; duplicates use first-seen order.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetThreadReadStates",
                service_name="chatto.api.v1.ThreadService",
                input=BatchGetThreadReadStatesRequest,
                output=BatchGetThreadReadStatesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_thread_participants(
        self,
        request: ListThreadParticipantsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListThreadParticipantsResponse:
        """
        Lists distinct authors of non-retracted replies, excluding erased users.
        The root author is included only if they also replied. Requires the same
        membership and message-read access as GetThreadEvents.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListThreadParticipants",
                service_name="chatto.api.v1.ThreadService",
                input=ListThreadParticipantsRequest,
                output=ListThreadParticipantsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_followed_threads(
        self,
        request: ListFollowedThreadsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListFollowedThreadsResponse:
        """
        Returns followed threads in rooms where the current user is a member.
        All threads also require message.read or an active relationship with
        message.read-interactions. Direct-message threads are returned only when
        include_direct_message_threads is true.
        The result includes enough root and latest-reply data for clients to render
        the list without extra per-thread fetches.
        Activity can reorder the live result between offset pages. After a thread
        activity update, clients must restart paging at offset zero.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListFollowedThreads",
                service_name="chatto.api.v1.ThreadService",
                input=ListFollowedThreadsRequest,
                output=ListFollowedThreadsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def follow_thread(
        self,
        request: FollowThreadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> FollowThreadResponse:
        """
        Follows a thread for the current user. Room membership plus message.read or
        an active relationship with message.read-interactions are required.
        Followed threads can be surfaced in clients and can participate in thread
        notification behavior.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FollowThread",
                service_name="chatto.api.v1.ThreadService",
                input=FollowThreadRequest,
                output=FollowThreadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def unfollow_thread(
        self,
        request: UnfollowThreadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UnfollowThreadResponse:
        """
        Stops following a thread for the current user. Room membership plus
        message.read or an active relationship with message.read-interactions are
        required. The response reports
        the resulting follow state so clients can update local UI immediately.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnfollowThread",
                service_name="chatto.api.v1.ThreadService",
                input=UnfollowThreadRequest,
                output=UnfollowThreadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_thread_events(
        self,
        request: GetThreadEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetThreadEventsResponse:
        """
        Returns one page of events in a message thread. Room membership is
        required. Reads also require message.read or an active relationship with
        message.read-interactions. Initial pages include the thread root message; cursor pages
        return replies in the requested direction.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadEvents",
                service_name="chatto.api.v1.ThreadService",
                input=GetThreadEventsRequest,
                output=GetThreadEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_thread_events_around(
        self,
        request: GetThreadEventsAroundRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetThreadEventsAroundResponse:
        """
        Returns a thread timeline window centered around a specific event. Use this
        to open a reply from a notification or search result in context. Returns
        NOT_FOUND when the thread root or anchor event is missing or hidden.
        Returns PERMISSION_DENIED when room membership is missing, both read modes
        are missing, or an interaction-scoped account has no relationship with the
        thread.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadEventsAround",
                service_name="chatto.api.v1.ThreadService",
                input=GetThreadEventsAroundRequest,
                output=GetThreadEventsAroundResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def mark_thread_as_read(
        self,
        request: MarkThreadAsReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> MarkThreadAsReadResponse:
        """
        Marks a thread timeline as read through the supplied event without changing
        the room-level read marker. Room membership plus message.read or an active
        relationship with message.read-interactions are required.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkThreadAsRead",
                service_name="chatto.api.v1.ThreadService",
                input=MarkThreadAsReadRequest,
                output=MarkThreadAsReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ThreadServiceSync(Protocol):
    """
    Manages thread follow state for the current user.
    """
    def get_thread_read_state(self, request: GetThreadReadStateRequest, ctx: RequestContext[GetThreadReadStateRequest, GetThreadReadStateResponse], /) -> GetThreadReadStateResponse:
        """
        Reads the current viewer's stored marker without changing it. Requires the
        same membership and read access as MarkThreadAsRead. Missing resources
        return NOT_FOUND; inaccessible resources return PERMISSION_DENIED.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_get_thread_read_states(self, request: BatchGetThreadReadStatesRequest, ctx: RequestContext[BatchGetThreadReadStatesRequest, BatchGetThreadReadStatesResponse], /) -> BatchGetThreadReadStatesResponse:
        """
        Reads up to 100 states under the same authorization as GetThreadReadState.
        Missing and inaccessible resources are omitted; duplicates use first-seen order.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_thread_participants(self, request: ListThreadParticipantsRequest, ctx: RequestContext[ListThreadParticipantsRequest, ListThreadParticipantsResponse], /) -> ListThreadParticipantsResponse:
        """
        Lists distinct authors of non-retracted replies, excluding erased users.
        The root author is included only if they also replied. Requires the same
        membership and message-read access as GetThreadEvents.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_followed_threads(self, request: ListFollowedThreadsRequest, ctx: RequestContext[ListFollowedThreadsRequest, ListFollowedThreadsResponse], /) -> ListFollowedThreadsResponse:
        """
        Returns followed threads in rooms where the current user is a member.
        All threads also require message.read or an active relationship with
        message.read-interactions. Direct-message threads are returned only when
        include_direct_message_threads is true.
        The result includes enough root and latest-reply data for clients to render
        the list without extra per-thread fetches.
        Activity can reorder the live result between offset pages. After a thread
        activity update, clients must restart paging at offset zero.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def follow_thread(self, request: FollowThreadRequest, ctx: RequestContext[FollowThreadRequest, FollowThreadResponse], /) -> FollowThreadResponse:
        """
        Follows a thread for the current user. Room membership plus message.read or
        an active relationship with message.read-interactions are required.
        Followed threads can be surfaced in clients and can participate in thread
        notification behavior.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def unfollow_thread(self, request: UnfollowThreadRequest, ctx: RequestContext[UnfollowThreadRequest, UnfollowThreadResponse], /) -> UnfollowThreadResponse:
        """
        Stops following a thread for the current user. Room membership plus
        message.read or an active relationship with message.read-interactions are
        required. The response reports
        the resulting follow state so clients can update local UI immediately.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_thread_events(self, request: GetThreadEventsRequest, ctx: RequestContext[GetThreadEventsRequest, GetThreadEventsResponse], /) -> GetThreadEventsResponse:
        """
        Returns one page of events in a message thread. Room membership is
        required. Reads also require message.read or an active relationship with
        message.read-interactions. Initial pages include the thread root message; cursor pages
        return replies in the requested direction.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_thread_events_around(self, request: GetThreadEventsAroundRequest, ctx: RequestContext[GetThreadEventsAroundRequest, GetThreadEventsAroundResponse], /) -> GetThreadEventsAroundResponse:
        """
        Returns a thread timeline window centered around a specific event. Use this
        to open a reply from a notification or search result in context. Returns
        NOT_FOUND when the thread root or anchor event is missing or hidden.
        Returns PERMISSION_DENIED when room membership is missing, both read modes
        are missing, or an interaction-scoped account has no relationship with the
        thread.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def mark_thread_as_read(self, request: MarkThreadAsReadRequest, ctx: RequestContext[MarkThreadAsReadRequest, MarkThreadAsReadResponse], /) -> MarkThreadAsReadResponse:
        """
        Marks a thread timeline as read through the supplied event without changing
        the room-level read marker. Room membership plus message.read or an active
        relationship with message.read-interactions are required.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in threads_pb.desc().services if s.type_name == 'chatto.api.v1.ThreadService')

class ThreadServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ThreadServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.ThreadService/GetThreadReadState": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetThreadReadState",
                        service_name="chatto.api.v1.ThreadService",
                        input=GetThreadReadStateRequest,
                        output=GetThreadReadStateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_thread_read_state,
                ),
                "/chatto.api.v1.ThreadService/BatchGetThreadReadStates": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetThreadReadStates",
                        service_name="chatto.api.v1.ThreadService",
                        input=BatchGetThreadReadStatesRequest,
                        output=BatchGetThreadReadStatesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_thread_read_states,
                ),
                "/chatto.api.v1.ThreadService/ListThreadParticipants": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListThreadParticipants",
                        service_name="chatto.api.v1.ThreadService",
                        input=ListThreadParticipantsRequest,
                        output=ListThreadParticipantsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_thread_participants,
                ),
                "/chatto.api.v1.ThreadService/ListFollowedThreads": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListFollowedThreads",
                        service_name="chatto.api.v1.ThreadService",
                        input=ListFollowedThreadsRequest,
                        output=ListFollowedThreadsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_followed_threads,
                ),
                "/chatto.api.v1.ThreadService/FollowThread": EndpointSync.unary(
                    method=MethodInfo(
                        name="FollowThread",
                        service_name="chatto.api.v1.ThreadService",
                        input=FollowThreadRequest,
                        output=FollowThreadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.follow_thread,
                ),
                "/chatto.api.v1.ThreadService/UnfollowThread": EndpointSync.unary(
                    method=MethodInfo(
                        name="UnfollowThread",
                        service_name="chatto.api.v1.ThreadService",
                        input=UnfollowThreadRequest,
                        output=UnfollowThreadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.unfollow_thread,
                ),
                "/chatto.api.v1.ThreadService/GetThreadEvents": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetThreadEvents",
                        service_name="chatto.api.v1.ThreadService",
                        input=GetThreadEventsRequest,
                        output=GetThreadEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_thread_events,
                ),
                "/chatto.api.v1.ThreadService/GetThreadEventsAround": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetThreadEventsAround",
                        service_name="chatto.api.v1.ThreadService",
                        input=GetThreadEventsAroundRequest,
                        output=GetThreadEventsAroundResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_thread_events_around,
                ),
                "/chatto.api.v1.ThreadService/MarkThreadAsRead": EndpointSync.unary(
                    method=MethodInfo(
                        name="MarkThreadAsRead",
                        service_name="chatto.api.v1.ThreadService",
                        input=MarkThreadAsReadRequest,
                        output=MarkThreadAsReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.mark_thread_as_read,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.ThreadService"


class ThreadServiceClientSync(ConnectClientSync):
    """
    Manages thread follow state for the current user.
    """
    def get_thread_read_state(
        self,
        request: GetThreadReadStateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetThreadReadStateResponse:
        """
        Reads the current viewer's stored marker without changing it. Requires the
        same membership and read access as MarkThreadAsRead. Missing resources
        return NOT_FOUND; inaccessible resources return PERMISSION_DENIED.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadReadState",
                service_name="chatto.api.v1.ThreadService",
                input=GetThreadReadStateRequest,
                output=GetThreadReadStateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def batch_get_thread_read_states(
        self,
        request: BatchGetThreadReadStatesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetThreadReadStatesResponse:
        """
        Reads up to 100 states under the same authorization as GetThreadReadState.
        Missing and inaccessible resources are omitted; duplicates use first-seen order.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetThreadReadStates",
                service_name="chatto.api.v1.ThreadService",
                input=BatchGetThreadReadStatesRequest,
                output=BatchGetThreadReadStatesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_thread_participants(
        self,
        request: ListThreadParticipantsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListThreadParticipantsResponse:
        """
        Lists distinct authors of non-retracted replies, excluding erased users.
        The root author is included only if they also replied. Requires the same
        membership and message-read access as GetThreadEvents.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListThreadParticipants",
                service_name="chatto.api.v1.ThreadService",
                input=ListThreadParticipantsRequest,
                output=ListThreadParticipantsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_followed_threads(
        self,
        request: ListFollowedThreadsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListFollowedThreadsResponse:
        """
        Returns followed threads in rooms where the current user is a member.
        All threads also require message.read or an active relationship with
        message.read-interactions. Direct-message threads are returned only when
        include_direct_message_threads is true.
        The result includes enough root and latest-reply data for clients to render
        the list without extra per-thread fetches.
        Activity can reorder the live result between offset pages. After a thread
        activity update, clients must restart paging at offset zero.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListFollowedThreads",
                service_name="chatto.api.v1.ThreadService",
                input=ListFollowedThreadsRequest,
                output=ListFollowedThreadsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def follow_thread(
        self,
        request: FollowThreadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> FollowThreadResponse:
        """
        Follows a thread for the current user. Room membership plus message.read or
        an active relationship with message.read-interactions are required.
        Followed threads can be surfaced in clients and can participate in thread
        notification behavior.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FollowThread",
                service_name="chatto.api.v1.ThreadService",
                input=FollowThreadRequest,
                output=FollowThreadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def unfollow_thread(
        self,
        request: UnfollowThreadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UnfollowThreadResponse:
        """
        Stops following a thread for the current user. Room membership plus
        message.read or an active relationship with message.read-interactions are
        required. The response reports
        the resulting follow state so clients can update local UI immediately.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnfollowThread",
                service_name="chatto.api.v1.ThreadService",
                input=UnfollowThreadRequest,
                output=UnfollowThreadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_thread_events(
        self,
        request: GetThreadEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetThreadEventsResponse:
        """
        Returns one page of events in a message thread. Room membership is
        required. Reads also require message.read or an active relationship with
        message.read-interactions. Initial pages include the thread root message; cursor pages
        return replies in the requested direction.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadEvents",
                service_name="chatto.api.v1.ThreadService",
                input=GetThreadEventsRequest,
                output=GetThreadEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_thread_events_around(
        self,
        request: GetThreadEventsAroundRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetThreadEventsAroundResponse:
        """
        Returns a thread timeline window centered around a specific event. Use this
        to open a reply from a notification or search result in context. Returns
        NOT_FOUND when the thread root or anchor event is missing or hidden.
        Returns PERMISSION_DENIED when room membership is missing, both read modes
        are missing, or an interaction-scoped account has no relationship with the
        thread.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadEventsAround",
                service_name="chatto.api.v1.ThreadService",
                input=GetThreadEventsAroundRequest,
                output=GetThreadEventsAroundResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def mark_thread_as_read(
        self,
        request: MarkThreadAsReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> MarkThreadAsReadResponse:
        """
        Marks a thread timeline as read through the supplied event without changing
        the room-level read marker. Room membership plus message.read or an active
        relationship with message.read-interactions are required.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkThreadAsRead",
                service_name="chatto.api.v1.ThreadService",
                input=MarkThreadAsReadRequest,
                output=MarkThreadAsReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
