# Generated from chatto/api/v1/user_status.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.5.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc
from protobuf.wkt import timestamp_pb

from ....buf.validate import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile
    from protobuf.wkt import Timestamp


_CustomUserStatusFields: TypeAlias = Literal["emoji", "text", "expires_at"]

class CustomUserStatus(Message[_CustomUserStatusFields]):
    """
    Custom status shown on a user profile, separate from presence.

    ```proto
    message chatto.api.v1.CustomUserStatus
    ```

    Attributes:
        emoji:
            Short emoji marker displayed with the status.

            ```proto
            string emoji = 1;
            ```
        text:
            User-written status text.

            ```proto
            string text = 2;
            ```
        expires_at:
            Optional time after which clients should stop showing the status.

            ```proto
            optional google.protobuf.Timestamp expires_at = 3;
            ```
    """

    __slots__ = ("emoji", "text", "expires_at")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            emoji: str = "",
            text: str = "",
            expires_at: Timestamp | None = None,
        ) -> None:
            pass

        emoji: str
        text: str
        expires_at: Timestamp | None

_SetCustomStatusRequestFields: TypeAlias = Literal["emoji", "text", "expires_at"]

class SetCustomStatusRequest(Message[_SetCustomStatusRequestFields]):
    """
    Request to replace the current user's complete custom status. Emoji and text
    are required. Omitted expires_at removes any previous expiry. Use
    DeleteCustomStatus to clear the status.

    ```proto
    message chatto.api.v1.SetCustomStatusRequest
    ```

    Attributes:
        emoji:
            Short emoji marker displayed with the status.

            ```proto
            string emoji = 1;
            ```
        text:
            User-written status text.

            ```proto
            string text = 2;
            ```
        expires_at:
            Optional future time after which clients should stop showing the status.

            ```proto
            optional google.protobuf.Timestamp expires_at = 3;
            ```
    """

    __slots__ = ("emoji", "text", "expires_at")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            emoji: str = "",
            text: str = "",
            expires_at: Timestamp | None = None,
        ) -> None:
            pass

        emoji: str
        text: str
        expires_at: Timestamp | None

_SetCustomStatusResponseFields: TypeAlias = Literal["status"]

class SetCustomStatusResponse(Message[_SetCustomStatusResponseFields]):
    """
    Result of setting the current user's complete custom status.

    ```proto
    message chatto.api.v1.SetCustomStatusResponse
    ```

    Attributes:
        status:
            Stored custom status after validation and normalization.

            ```proto
            optional chatto.api.v1.CustomUserStatus status = 1;
            ```
    """

    __slots__ = ("status",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            status: CustomUserStatus | None = None,
        ) -> None:
            pass

        status: CustomUserStatus | None

_DeleteCustomStatusRequestFields: TypeAlias = NoReturn

class DeleteCustomStatusRequest(Message[_DeleteCustomStatusRequestFields]):
    """
    Request to delete the current user's custom status.

    ```proto
    message chatto.api.v1.DeleteCustomStatusRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_DeleteCustomStatusResponseFields: TypeAlias = Literal["status"]

class DeleteCustomStatusResponse(Message[_DeleteCustomStatusResponseFields]):
    """
    Result of deleting the current user's custom status.

    ```proto
    message chatto.api.v1.DeleteCustomStatusResponse
    ```

    Attributes:
        status:
            Current custom status after the operation. Usually absent after a clear.

            ```proto
            optional chatto.api.v1.CustomUserStatus status = 1;
            ```
    """

    __slots__ = ("status",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            status: CustomUserStatus | None = None,
        ) -> None:
            pass

        status: CustomUserStatus | None


_DESC = file_desc(
    b'\n\x1fchatto/api/v1/user_status.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\x8d\x01\n\x10CustomUserStatus\x12\x1f\n\x05emoji\x18\x01 \x01(\tR\x05emojiB\t\xbaH\x06r\x04\x10\x01\x18\x10\x12\x1d\n\x04text\x18\x02 \x01(\tR\x04textB\t\xbaH\x06r\x04\x10\x01\x18d\x129\n\nexpires_at\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampR\texpiresAt"}\n\x16SetCustomStatusRequest\x12\x14\n\x05emoji\x18\x01 \x01(\tR\x05emoji\x12\x12\n\x04text\x18\x02 \x01(\tR\x04text\x129\n\nexpires_at\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampR\texpiresAt"R\n\x17SetCustomStatusResponse\x127\n\x06status\x18\x01 \x01(\x0b2\x1f.chatto.api.v1.CustomUserStatusR\x06status"\x1b\n\x19DeleteCustomStatusRequest"U\n\x1aDeleteCustomStatusResponse\x127\n\x06status\x18\x01 \x01(\x0b2\x1f.chatto.api.v1.CustomUserStatusR\x06statusBz\n\x11com.chatto.api.v1B\x0fUserStatusProtoP\x01\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3',
    [
        validate_pb.desc(),
        timestamp_pb.desc(),
    ],
    {
        "CustomUserStatus": CustomUserStatus,
        "SetCustomStatusRequest": SetCustomStatusRequest,
        "SetCustomStatusResponse": SetCustomStatusResponse,
        "DeleteCustomStatusRequest": DeleteCustomStatusRequest,
        "DeleteCustomStatusResponse": DeleteCustomStatusResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `chatto/api/v1/user_status.proto`."""
    return _DESC
