# Generated from chatto/discovery/v1/server.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.2.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from ...api.v1 import server_pb

if TYPE_CHECKING:
    from protobuf import DescFile

    from ...api.v1.server_pb import ServerLogin, ServerPublicProfile


_GetServerRequestFields: TypeAlias = NoReturn

class GetServerRequest(Message[_GetServerRequestFields]):
    """
    Request for public server metadata.

    ```proto
    message chatto.discovery.v1.GetServerRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_GetServerResponseFields: TypeAlias = Literal["profile", "login"]

class GetServerResponse(Message[_GetServerResponseFields]):
    """
    Public metadata clients need before they can authenticate or render the
    initial server view.

    ```proto
    message chatto.discovery.v1.GetServerResponse
    ```

    Attributes:
        profile:
            Public server profile and branding.

            ```proto
            optional chatto.api.v1.ServerPublicProfile profile = 1;
            ```
        login:
            Login and registration options.

            ```proto
            optional chatto.api.v1.ServerLogin login = 2;
            ```
    """

    __slots__ = ("profile", "login")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            profile: ServerPublicProfile | None = None,
            login: ServerLogin | None = None,
        ) -> None:
            pass

        profile: ServerPublicProfile | None
        login: ServerLogin | None


_DESC = file_desc(
    b'\n chatto/discovery/v1/server.proto\x12\x13chatto.discovery.v1\x1a\x1achatto/api/v1/server.proto"\x12\n\x10GetServerRequest"\x83\x01\n\x11GetServerResponse\x12<\n\x07profile\x18\x01 \x01(\x0b2".chatto.api.v1.ServerPublicProfileR\x07profile\x120\n\x05login\x18\x02 \x01(\x0b2\x1a.chatto.api.v1.ServerLoginR\x05login2y\n\x16ServerDiscoveryService\x12_\n\tGetServer\x12%.chatto.discovery.v1.GetServerRequest\x1a&.chatto.discovery.v1.GetServerResponse"\x03\x90\x02\x01B\x94\x01\n\x17com.chatto.discovery.v1B\x0bServerProtoP\x01\xa2\x02\x03CDX\xaa\x02\x13Chatto.Discovery.V1\xca\x02\x13Chatto\\Discovery\\V1\xe2\x02\x1fChatto\\Discovery\\V1\\GPBMetadata\xea\x02\x15Chatto::Discovery::V1b\x06proto3',
    [
        server_pb.desc(),
    ],
    {
        "GetServerRequest": GetServerRequest,
        "GetServerResponse": GetServerResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `chatto/discovery/v1/server.proto`."""
    return _DESC
