# Generated from chatto/admin/v1/members.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import members_pb
from .members_pb import AssignRoleRequest, AssignRoleResponse, BatchGetMembersRequest, BatchGetMembersResponse, ChangeUserPasswordRequest, ChangeUserPasswordResponse, ClearUsernameCooldownRequest, ClearUsernameCooldownResponse, DeleteUserRequest, DeleteUserResponse, GetMemberRequest, GetMemberResponse, ListMembersRequest, ListMembersResponse, RevokeRoleRequest, RevokeRoleResponse, UpdateUserRequest, UpdateUserResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class AdminUserService(Protocol):
    """
    Server-admin user management commands and member-detail reads.
    """
    async def list_members(self, request: ListMembersRequest, ctx: RequestContext[ListMembersRequest, ListMembersResponse], /) -> ListMembersResponse:
        """
        Lists server members for the admin members screen. Requires
        admin.view-users.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_member(self, request: GetMemberRequest, ctx: RequestContext[GetMemberRequest, GetMemberResponse], /) -> GetMemberResponse:
        """
        Gets one server member plus role/permission metadata for admin details.
        Requires admin.view-users. Returns NOT_FOUND when the user does not exist.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_get_members(self, request: BatchGetMembersRequest, ctx: RequestContext[BatchGetMembersRequest, BatchGetMembersResponse], /) -> BatchGetMembersResponse:
        """
        Gets server member rows for multiple users. Requires admin.view-users.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def assign_role(self, request: AssignRoleRequest, ctx: RequestContext[AssignRoleRequest, AssignRoleResponse], /) -> AssignRoleResponse:
        """
        Assigns a role to a user. Requires role.assign, and non-owner callers may
        only assign roles whose granted authority they already possess.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def revoke_role(self, request: RevokeRoleRequest, ctx: RequestContext[RevokeRoleRequest, RevokeRoleResponse], /) -> RevokeRoleResponse:
        """
        Revokes a role from a user. Requires role.assign, and non-owner callers may
        only revoke roles whose permission decisions are within their authority.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_user(self, request: UpdateUserRequest, ctx: RequestContext[UpdateUserRequest, UpdateUserResponse], /) -> UpdateUserResponse:
        """
        Updates a human user's login and/or display name without applying the
        username-change cooldown. Requires user.manage-accounts, including when
        the caller targets their own account. Preserves the cooldown timestamp.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def change_user_password(self, request: ChangeUserPasswordRequest, ctx: RequestContext[ChangeUserPasswordRequest, ChangeUserPasswordResponse], /) -> ChangeUserPasswordResponse:
        """
        Updates another user's password as an admin action. Requires
        user.manage-accounts and a fresh credential for the caller; the caller
        cannot target their own account.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def clear_username_cooldown(self, request: ClearUsernameCooldownRequest, ctx: RequestContext[ClearUsernameCooldownRequest, ClearUsernameCooldownResponse], /) -> ClearUsernameCooldownResponse:
        """
        Clears the target user's self-service username-change cooldown. Requires
        user.manage-accounts, including when the caller targets their own account.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_user(self, request: DeleteUserRequest, ctx: RequestContext[DeleteUserRequest, DeleteUserResponse], /) -> DeleteUserResponse:
        """
        Deletes a user account as an admin action. Requires user.delete-any for
        other users or user.delete-self for the caller.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in members_pb.desc().services if s.type_name == 'chatto.admin.v1.AdminUserService')

class AdminUserServiceASGIApplication(ConnectASGIApplication[AdminUserService]):
    def __init__(
        self,
        service: AdminUserService | AsyncGenerator[AdminUserService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.admin.v1.AdminUserService/ListMembers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListMembers",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=ListMembersRequest,
                        output=ListMembersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_members,
                ),
                "/chatto.admin.v1.AdminUserService/GetMember": Endpoint.unary(
                    method=MethodInfo(
                        name="GetMember",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=GetMemberRequest,
                        output=GetMemberResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_member,
                ),
                "/chatto.admin.v1.AdminUserService/BatchGetMembers": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetMembers",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=BatchGetMembersRequest,
                        output=BatchGetMembersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_members,
                ),
                "/chatto.admin.v1.AdminUserService/AssignRole": Endpoint.unary(
                    method=MethodInfo(
                        name="AssignRole",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=AssignRoleRequest,
                        output=AssignRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.assign_role,
                ),
                "/chatto.admin.v1.AdminUserService/RevokeRole": Endpoint.unary(
                    method=MethodInfo(
                        name="RevokeRole",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=RevokeRoleRequest,
                        output=RevokeRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.revoke_role,
                ),
                "/chatto.admin.v1.AdminUserService/UpdateUser": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateUser",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=UpdateUserRequest,
                        output=UpdateUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_user,
                ),
                "/chatto.admin.v1.AdminUserService/ChangeUserPassword": Endpoint.unary(
                    method=MethodInfo(
                        name="ChangeUserPassword",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=ChangeUserPasswordRequest,
                        output=ChangeUserPasswordResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.change_user_password,
                ),
                "/chatto.admin.v1.AdminUserService/ClearUsernameCooldown": Endpoint.unary(
                    method=MethodInfo(
                        name="ClearUsernameCooldown",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=ClearUsernameCooldownRequest,
                        output=ClearUsernameCooldownResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.clear_username_cooldown,
                ),
                "/chatto.admin.v1.AdminUserService/DeleteUser": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteUser",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=DeleteUserRequest,
                        output=DeleteUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_user,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.admin.v1.AdminUserService"


class AdminUserServiceClient(ConnectClient):
    """
    Server-admin user management commands and member-detail reads.
    """
    async def list_members(
        self,
        request: ListMembersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListMembersResponse:
        """
        Lists server members for the admin members screen. Requires
        admin.view-users.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMembers",
                service_name="chatto.admin.v1.AdminUserService",
                input=ListMembersRequest,
                output=ListMembersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_member(
        self,
        request: GetMemberRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetMemberResponse:
        """
        Gets one server member plus role/permission metadata for admin details.
        Requires admin.view-users. Returns NOT_FOUND when the user does not exist.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetMember",
                service_name="chatto.admin.v1.AdminUserService",
                input=GetMemberRequest,
                output=GetMemberResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_members(
        self,
        request: BatchGetMembersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetMembersResponse:
        """
        Gets server member rows for multiple users. Requires admin.view-users.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetMembers",
                service_name="chatto.admin.v1.AdminUserService",
                input=BatchGetMembersRequest,
                output=BatchGetMembersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def assign_role(
        self,
        request: AssignRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AssignRoleResponse:
        """
        Assigns a role to a user. Requires role.assign, and non-owner callers may
        only assign roles whose granted authority they already possess.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AssignRole",
                service_name="chatto.admin.v1.AdminUserService",
                input=AssignRoleRequest,
                output=AssignRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def revoke_role(
        self,
        request: RevokeRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> RevokeRoleResponse:
        """
        Revokes a role from a user. Requires role.assign, and non-owner callers may
        only revoke roles whose permission decisions are within their authority.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeRole",
                service_name="chatto.admin.v1.AdminUserService",
                input=RevokeRoleRequest,
                output=RevokeRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_user(
        self,
        request: UpdateUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateUserResponse:
        """
        Updates a human user's login and/or display name without applying the
        username-change cooldown. Requires user.manage-accounts, including when
        the caller targets their own account. Preserves the cooldown timestamp.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateUser",
                service_name="chatto.admin.v1.AdminUserService",
                input=UpdateUserRequest,
                output=UpdateUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def change_user_password(
        self,
        request: ChangeUserPasswordRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ChangeUserPasswordResponse:
        """
        Updates another user's password as an admin action. Requires
        user.manage-accounts and a fresh credential for the caller; the caller
        cannot target their own account.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ChangeUserPassword",
                service_name="chatto.admin.v1.AdminUserService",
                input=ChangeUserPasswordRequest,
                output=ChangeUserPasswordResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def clear_username_cooldown(
        self,
        request: ClearUsernameCooldownRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ClearUsernameCooldownResponse:
        """
        Clears the target user's self-service username-change cooldown. Requires
        user.manage-accounts, including when the caller targets their own account.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ClearUsernameCooldown",
                service_name="chatto.admin.v1.AdminUserService",
                input=ClearUsernameCooldownRequest,
                output=ClearUsernameCooldownResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_user(
        self,
        request: DeleteUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteUserResponse:
        """
        Deletes a user account as an admin action. Requires user.delete-any for
        other users or user.delete-self for the caller.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteUser",
                service_name="chatto.admin.v1.AdminUserService",
                input=DeleteUserRequest,
                output=DeleteUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class AdminUserServiceSync(Protocol):
    """
    Server-admin user management commands and member-detail reads.
    """
    def list_members(self, request: ListMembersRequest, ctx: RequestContext[ListMembersRequest, ListMembersResponse], /) -> ListMembersResponse:
        """
        Lists server members for the admin members screen. Requires
        admin.view-users.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_member(self, request: GetMemberRequest, ctx: RequestContext[GetMemberRequest, GetMemberResponse], /) -> GetMemberResponse:
        """
        Gets one server member plus role/permission metadata for admin details.
        Requires admin.view-users. Returns NOT_FOUND when the user does not exist.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_get_members(self, request: BatchGetMembersRequest, ctx: RequestContext[BatchGetMembersRequest, BatchGetMembersResponse], /) -> BatchGetMembersResponse:
        """
        Gets server member rows for multiple users. Requires admin.view-users.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def assign_role(self, request: AssignRoleRequest, ctx: RequestContext[AssignRoleRequest, AssignRoleResponse], /) -> AssignRoleResponse:
        """
        Assigns a role to a user. Requires role.assign, and non-owner callers may
        only assign roles whose granted authority they already possess.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def revoke_role(self, request: RevokeRoleRequest, ctx: RequestContext[RevokeRoleRequest, RevokeRoleResponse], /) -> RevokeRoleResponse:
        """
        Revokes a role from a user. Requires role.assign, and non-owner callers may
        only revoke roles whose permission decisions are within their authority.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_user(self, request: UpdateUserRequest, ctx: RequestContext[UpdateUserRequest, UpdateUserResponse], /) -> UpdateUserResponse:
        """
        Updates a human user's login and/or display name without applying the
        username-change cooldown. Requires user.manage-accounts, including when
        the caller targets their own account. Preserves the cooldown timestamp.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def change_user_password(self, request: ChangeUserPasswordRequest, ctx: RequestContext[ChangeUserPasswordRequest, ChangeUserPasswordResponse], /) -> ChangeUserPasswordResponse:
        """
        Updates another user's password as an admin action. Requires
        user.manage-accounts and a fresh credential for the caller; the caller
        cannot target their own account.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def clear_username_cooldown(self, request: ClearUsernameCooldownRequest, ctx: RequestContext[ClearUsernameCooldownRequest, ClearUsernameCooldownResponse], /) -> ClearUsernameCooldownResponse:
        """
        Clears the target user's self-service username-change cooldown. Requires
        user.manage-accounts, including when the caller targets their own account.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_user(self, request: DeleteUserRequest, ctx: RequestContext[DeleteUserRequest, DeleteUserResponse], /) -> DeleteUserResponse:
        """
        Deletes a user account as an admin action. Requires user.delete-any for
        other users or user.delete-self for the caller.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in members_pb.desc().services if s.type_name == 'chatto.admin.v1.AdminUserService')

class AdminUserServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AdminUserServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/chatto.admin.v1.AdminUserService/ListMembers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListMembers",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=ListMembersRequest,
                        output=ListMembersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_members,
                ),
                "/chatto.admin.v1.AdminUserService/GetMember": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetMember",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=GetMemberRequest,
                        output=GetMemberResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_member,
                ),
                "/chatto.admin.v1.AdminUserService/BatchGetMembers": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetMembers",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=BatchGetMembersRequest,
                        output=BatchGetMembersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_members,
                ),
                "/chatto.admin.v1.AdminUserService/AssignRole": EndpointSync.unary(
                    method=MethodInfo(
                        name="AssignRole",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=AssignRoleRequest,
                        output=AssignRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.assign_role,
                ),
                "/chatto.admin.v1.AdminUserService/RevokeRole": EndpointSync.unary(
                    method=MethodInfo(
                        name="RevokeRole",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=RevokeRoleRequest,
                        output=RevokeRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.revoke_role,
                ),
                "/chatto.admin.v1.AdminUserService/UpdateUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateUser",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=UpdateUserRequest,
                        output=UpdateUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_user,
                ),
                "/chatto.admin.v1.AdminUserService/ChangeUserPassword": EndpointSync.unary(
                    method=MethodInfo(
                        name="ChangeUserPassword",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=ChangeUserPasswordRequest,
                        output=ChangeUserPasswordResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.change_user_password,
                ),
                "/chatto.admin.v1.AdminUserService/ClearUsernameCooldown": EndpointSync.unary(
                    method=MethodInfo(
                        name="ClearUsernameCooldown",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=ClearUsernameCooldownRequest,
                        output=ClearUsernameCooldownResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.clear_username_cooldown,
                ),
                "/chatto.admin.v1.AdminUserService/DeleteUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteUser",
                        service_name="chatto.admin.v1.AdminUserService",
                        input=DeleteUserRequest,
                        output=DeleteUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_user,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.admin.v1.AdminUserService"


class AdminUserServiceClientSync(ConnectClientSync):
    """
    Server-admin user management commands and member-detail reads.
    """
    def list_members(
        self,
        request: ListMembersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListMembersResponse:
        """
        Lists server members for the admin members screen. Requires
        admin.view-users.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMembers",
                service_name="chatto.admin.v1.AdminUserService",
                input=ListMembersRequest,
                output=ListMembersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_member(
        self,
        request: GetMemberRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetMemberResponse:
        """
        Gets one server member plus role/permission metadata for admin details.
        Requires admin.view-users. Returns NOT_FOUND when the user does not exist.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetMember",
                service_name="chatto.admin.v1.AdminUserService",
                input=GetMemberRequest,
                output=GetMemberResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def batch_get_members(
        self,
        request: BatchGetMembersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchGetMembersResponse:
        """
        Gets server member rows for multiple users. Requires admin.view-users.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetMembers",
                service_name="chatto.admin.v1.AdminUserService",
                input=BatchGetMembersRequest,
                output=BatchGetMembersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def assign_role(
        self,
        request: AssignRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AssignRoleResponse:
        """
        Assigns a role to a user. Requires role.assign, and non-owner callers may
        only assign roles whose granted authority they already possess.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AssignRole",
                service_name="chatto.admin.v1.AdminUserService",
                input=AssignRoleRequest,
                output=AssignRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def revoke_role(
        self,
        request: RevokeRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> RevokeRoleResponse:
        """
        Revokes a role from a user. Requires role.assign, and non-owner callers may
        only revoke roles whose permission decisions are within their authority.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeRole",
                service_name="chatto.admin.v1.AdminUserService",
                input=RevokeRoleRequest,
                output=RevokeRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def update_user(
        self,
        request: UpdateUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateUserResponse:
        """
        Updates a human user's login and/or display name without applying the
        username-change cooldown. Requires user.manage-accounts, including when
        the caller targets their own account. Preserves the cooldown timestamp.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateUser",
                service_name="chatto.admin.v1.AdminUserService",
                input=UpdateUserRequest,
                output=UpdateUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def change_user_password(
        self,
        request: ChangeUserPasswordRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ChangeUserPasswordResponse:
        """
        Updates another user's password as an admin action. Requires
        user.manage-accounts and a fresh credential for the caller; the caller
        cannot target their own account.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ChangeUserPassword",
                service_name="chatto.admin.v1.AdminUserService",
                input=ChangeUserPasswordRequest,
                output=ChangeUserPasswordResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def clear_username_cooldown(
        self,
        request: ClearUsernameCooldownRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ClearUsernameCooldownResponse:
        """
        Clears the target user's self-service username-change cooldown. Requires
        user.manage-accounts, including when the caller targets their own account.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ClearUsernameCooldown",
                service_name="chatto.admin.v1.AdminUserService",
                input=ClearUsernameCooldownRequest,
                output=ClearUsernameCooldownResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_user(
        self,
        request: DeleteUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteUserResponse:
        """
        Deletes a user account as an admin action. Requires user.delete-any for
        other users or user.delete-self for the caller.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteUser",
                service_name="chatto.admin.v1.AdminUserService",
                input=DeleteUserRequest,
                output=DeleteUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
